In [3]:
from googleapiclient.discovery import build
import random
from datetime import datetime, timedelta
import csv
import pandas as pd

In [4]:
YouTube_API_Key = 'AIzaSyC647_bWjOlvBk07WRjzIKyrKXMK3e2Juk'
youtube = build('youtube', 'v3', developerKey=YouTube_API_Key)

In [5]:
fox_channel_id = 'UCXIJgqnII2ZOINSWNOGFThA'
ap_channel_id = 'UC52X5wxOL_s5yw0dQk7NtgA'
vice_channel_id = 'UCn8zNIfYAQNdrFRrr8oibKw'
abc_channel_id = 'UCBi2mrWuNuyYy4gbM6fU18Q'
msnbc_channel_id = 'UCaXkIU1QidjPwiAYu6GcHjg'
vox_channel_id = 'UCLXo7UDZvByw2ixzpQCufnA'
SteveTurley_channel_id = 'UCCsiAKRKcgzA_372WbXNBaw'
KimIversen_channel_id = 'UCoJTOwZxbvq8Al8Qat2zgTA'
RobertReich_channel_id = 'UCuDv5p8E-evaRSh542hDV5g'

## 1. Helper Functions

In [6]:
def scrape_urls(channel_id, topic, max_result, start_date, end_date):
    ''' 
    Scrape YouTube news channels and obtain a list of topic relevant video urls
    
    Args:
        channel_id(str): The news channel id from its source page
        topic(str): The textual search terms to match
        max_result(int): maximum number of items (urls) returned in result set
        start_date(str): DateTime
        end_date(str): DateTime
    Return: A list of scraped URLs
    '''

    urls_lst = []
    request = youtube.search().list(
    part='snippet',
    channelId=channel_id,
    maxResults=max_result,
    q=topic,
    publishedAfter=start_date,
    publishedBefore=end_date
    )
    response = request.execute()
    
    # Not consider order because for each channel in each month 50 videos on the given topic should be exhaustive enough
    video_urls = ['https://www.youtube.com/watch?v=' + item['id']['videoId'] for item in response['items']]
    for url in video_urls:
        urls_lst.append(url)
        
    return urls_lst

In [7]:
def generate_start_end_time(year):
    ''' 
    Generate start dates and end dates for a given year to put into YouTube
    url query
    
    Args:
        year(int): The target year with target monthly start and end dates
    Return: 2 lists of date, one for all start dates and one for all end dates 
    '''

    start_dates = []
    end_dates = []
    
    for month in range(1, 13):
        start_date = datetime(year, month, 1, 0, 0, 0)
        last_day = datetime(year, month, 1)
        last_day = last_day.replace(month=(month % 12) + 1, day=1, hour=0, minute=0, second=0, microsecond=0)
        last_day -= timedelta(seconds=1)

        start_dates.append(start_date.isoformat() + 'Z')
        end_dates.append(last_day.isoformat() + 'Z')

    return start_dates, end_dates

In [7]:
start_dates, end_dates = generate_start_end_time(2020)
print('Half year start: ', start_dates[:6])
print('Half year end: ', end_dates[:6])

Half year start:  ['2020-01-01T00:00:00Z', '2020-02-01T00:00:00Z', '2020-03-01T00:00:00Z', '2020-04-01T00:00:00Z', '2020-05-01T00:00:00Z', '2020-06-01T00:00:00Z']
Half year end:  ['2020-01-31T23:59:59Z', '2020-02-29T23:59:59Z', '2020-03-31T23:59:59Z', '2020-04-30T23:59:59Z', '2020-05-31T23:59:59Z', '2020-06-30T23:59:59Z']


## 2. Scrape 2020 Videos Links

In [11]:
# First 3 months due to scraping quota
start_dates, end_dates = generate_start_end_time(2020)
channel_id = fox_channel_id
topic = 'covid19'
max_result = 30 

fox_urls_lst_yearly = []

for _, (start_date, end_date) in enumerate(zip(start_dates[:3], end_dates[:3])):
    fox_urls_lst_monthly = scrape_urls(channel_id, topic, max_result, start_date, end_date)
    fox_urls_lst_yearly.append(fox_urls_lst_monthly)

print(fox_urls_lst_yearly)

[[], [], ['https://www.youtube.com/watch?v=d1eEWihvwpQ', 'https://www.youtube.com/watch?v=gkR0jipzPRA', 'https://www.youtube.com/watch?v=EbyPW8lJX2E', 'https://www.youtube.com/watch?v=0Hrqi18Ltyw', 'https://www.youtube.com/watch?v=xhpqX1NbusQ', 'https://www.youtube.com/watch?v=T3mVLmebO3M', 'https://www.youtube.com/watch?v=aSBWlKC7reM', 'https://www.youtube.com/watch?v=toy4lVq1hww', 'https://www.youtube.com/watch?v=vjg3FW7YVFI', 'https://www.youtube.com/watch?v=mK3dx97W_AM', 'https://www.youtube.com/watch?v=DHBFGzy3GPw', 'https://www.youtube.com/watch?v=Pg2ITlDftWg', 'https://www.youtube.com/watch?v=CUNTjP3stIM', 'https://www.youtube.com/watch?v=ETh76m_mNUg', 'https://www.youtube.com/watch?v=brVMi-ddr9Q'], ['https://www.youtube.com/watch?v=lMAVBHDIeDA', 'https://www.youtube.com/watch?v=jk_jrlgvTdo', 'https://www.youtube.com/watch?v=ljNIAaXlMbU', 'https://www.youtube.com/watch?v=_HGTvjC0xrw', 'https://www.youtube.com/watch?v=BbEMphv9qzs', 'https://www.youtube.com/watch?v=y-DXEogwVXo', '

### 2.1 Fox 2020

In [ ]:
# Jan, Fab, March
start_dates, end_dates = generate_start_end_time(2020)
channel_id = fox_channel_id
topic = 'covid19'
max_result = 30
fox_urls_lst_yearly = []

for _, (start_date, end_date) in enumerate(zip(start_dates[:3], end_dates[:3])):
    fox_urls_lst_monthly = scrape_urls(channel_id, topic, max_result, start_date, end_date)
    
    if fox_urls_lst_yearly:
        fox_urls_lst_yearly.append([''])
    
    fox_urls_lst_yearly.extend(fox_urls_lst_monthly)

In [20]:
# April
fox_urls_lst_yearly4 = scrape_urls(channel_id, topic, max_result, start_dates[3], end_dates[3])

In [29]:
# May
fox_urls_lst_yearly5 = scrape_urls(channel_id, topic, max_result, start_dates[4], end_dates[4])

In [33]:
# June
fox_urls_lst_yearly6 = scrape_urls(channel_id, topic, max_result, start_dates[5], end_dates[5])

In [37]:
# July
fox_urls_lst_yearly7 = scrape_urls(channel_id, topic, max_result, start_dates[6], end_dates[6])

In [39]:
# August
fox_urls_lst_yearly8 = scrape_urls(channel_id, topic, max_result, start_dates[7], end_dates[7])

In [41]:
# September
fox_urls_lst_yearly9 = scrape_urls(channel_id, topic, max_result, start_dates[8], end_dates[8])

In [43]:
# October
fox_urls_lst_yearly10 = scrape_urls(channel_id, topic, max_result, start_dates[9], end_dates[9])

In [45]:
# November
fox_urls_lst_yearly11 = scrape_urls(channel_id, topic, max_result, start_dates[10], end_dates[10])

In [51]:
# December
fox_urls_lst_yearly12 = scrape_urls(channel_id, topic, max_result, start_dates[11], '2020-12-31T23:59:59Z')

In [54]:
fox_yearly_lst = [fox_urls_lst_yearly, fox_urls_lst_yearly4,
                         fox_urls_lst_yearly5, fox_urls_lst_yearly6,
                         fox_urls_lst_yearly7, fox_urls_lst_yearly8,
                         fox_urls_lst_yearly9, fox_urls_lst_yearly10,
                         fox_urls_lst_yearly11, fox_urls_lst_yearly12]
with open("/Users/itsyuzhou/Autumn2023/MA_thesis/fox_urls.csv", mode='w', newline='') as file:
    writer = csv.writer(file)

    for urls_monthly in fox_yearly_lst:
        for url in urls_monthly:
            writer.writerow([url])
        writer.writerow([])

In [135]:
total_video = 0
month = 2
monthly_videos_counts = []
for url_lst in fox_yearly_lst:
    month += 1
    monthly_videos_counts.append((month, len(url_lst)))

print(monthly_videos_counts)

for (month, monthly_count) in monthly_videos_counts:
    total_video += monthly_count
print("Fox News 2020 total video counts=", total_video)

[(3, 21), (4, 10), (5, 9), (6, 5), (7, 7), (8, 2), (9, 5), (10, 8), (11, 2), (12, 5)]
Fox News 2020 total video counts= 74


### 2.2 VICE 2020

In [159]:
start_dates, end_dates = generate_start_end_time(2020)
channel_id = vice_channel_id
topic = 'covid'
max_result = 30

In [138]:
# January
vice_urls_lst1 = scrape_urls(channel_id, topic, max_result, start_dates[0], end_dates[0])

['https://www.youtube.com/watch?v=_FyHhC3Y8Fc',
 'https://www.youtube.com/watch?v=GqipkDb0KGE',
 'https://www.youtube.com/watch?v=-WKmPiv2FmQ',
 'https://www.youtube.com/watch?v=gs26R56d3ww',
 'https://www.youtube.com/watch?v=pdlyyulxiy0',
 'https://www.youtube.com/watch?v=Lld8KpTW8RA',
 'https://www.youtube.com/watch?v=tGEBu0rP9Yw',
 'https://www.youtube.com/watch?v=6xOrWEbs_3k',
 'https://www.youtube.com/watch?v=Y0IdDh7iqBQ']

In [66]:
# Feburary
vice_urls_lst2 = scrape_urls(channel_id, topic, max_result, start_dates[1], end_dates[1])

In [141]:
# March
vice_urls_lst3 = scrape_urls(channel_id, topic, max_result, start_dates[2], end_dates[2])
vice_urls_lst3

['https://www.youtube.com/watch?v=3PttvhYlV2Q',
 'https://www.youtube.com/watch?v=yFgGcKOzGJU',
 'https://www.youtube.com/watch?v=ehTD_d8qR20',
 'https://www.youtube.com/watch?v=PdoogdEU6lY',
 'https://www.youtube.com/watch?v=vcCBacPWLrc',
 'https://www.youtube.com/watch?v=vfE9ZYgc588',
 'https://www.youtube.com/watch?v=y6oCN_ZSOlM',
 'https://www.youtube.com/watch?v=mmJtb-22sUQ',
 'https://www.youtube.com/watch?v=LMMU2daYtWY',
 'https://www.youtube.com/watch?v=7854Z9Bi2JQ',
 'https://www.youtube.com/watch?v=qAs12uIUALY',
 'https://www.youtube.com/watch?v=0XR1YWZH2Fs',
 'https://www.youtube.com/watch?v=ac43pFgzI8U',
 'https://www.youtube.com/watch?v=cJp6P3DRWhc',
 'https://www.youtube.com/watch?v=vo1BzyBwZ1E',
 'https://www.youtube.com/watch?v=OizZtjW6lFo',
 'https://www.youtube.com/watch?v=j8qgi99asoI',
 'https://www.youtube.com/watch?v=V3kssmNUh0g',
 'https://www.youtube.com/watch?v=Sn1ggsuE5SU',
 'https://www.youtube.com/watch?v=sBcgUYye8K8',
 'https://www.youtube.com/watch?v=hdVwCd

In [143]:
# April
vice_urls_lst4 = scrape_urls(channel_id, topic, max_result, start_dates[3], end_dates[3])
vice_urls_lst4

['https://www.youtube.com/watch?v=dJUAkqx4RsE',
 'https://www.youtube.com/watch?v=k6Al9UyW2ck',
 'https://www.youtube.com/watch?v=Zo68XHio_t4',
 'https://www.youtube.com/watch?v=J0tHjl6bSfE',
 'https://www.youtube.com/watch?v=-aGUuA5aDic',
 'https://www.youtube.com/watch?v=DcdoSp6OMGo',
 'https://www.youtube.com/watch?v=k5OAjnveyJo',
 'https://www.youtube.com/watch?v=MHSpVx5REyE',
 'https://www.youtube.com/watch?v=_fjMCVYPBcw',
 'https://www.youtube.com/watch?v=bpdEk-gBAIo',
 'https://www.youtube.com/watch?v=0bhajBydUu8',
 'https://www.youtube.com/watch?v=8epjMRG8S5o',
 'https://www.youtube.com/watch?v=-Di8iHgdc8g',
 'https://www.youtube.com/watch?v=YbmR7jNoKis',
 'https://www.youtube.com/watch?v=voA0cS1JiGQ',
 'https://www.youtube.com/watch?v=skPk2o3CCRY',
 'https://www.youtube.com/watch?v=Qn4d2J_TAU4',
 'https://www.youtube.com/watch?v=Z33VctxsjQw',
 'https://www.youtube.com/watch?v=GEG67_bjvYQ',
 'https://www.youtube.com/watch?v=kTHbMAR6ZuQ',
 'https://www.youtube.com/watch?v=_jZ0rY

In [147]:
# May
vice_urls_lst5 = scrape_urls(channel_id, topic, max_result, start_dates[4], end_dates[4])
vice_urls_lst5

['https://www.youtube.com/watch?v=8Q26YeiYMHM',
 'https://www.youtube.com/watch?v=6hbNrrrdEus',
 'https://www.youtube.com/watch?v=Id9DUn1RfOk',
 'https://www.youtube.com/watch?v=gXTeg5LAvN8',
 'https://www.youtube.com/watch?v=pRNMljWwVSk',
 'https://www.youtube.com/watch?v=o3Qxd25g9Sc',
 'https://www.youtube.com/watch?v=7HSKh4DfDMo',
 'https://www.youtube.com/watch?v=PF3lPwk27Nk',
 'https://www.youtube.com/watch?v=jMAavnirJPM',
 'https://www.youtube.com/watch?v=HiATC4m3Y2o',
 'https://www.youtube.com/watch?v=h8Jmf6nVoQo',
 'https://www.youtube.com/watch?v=VYOJfjKvXzo',
 'https://www.youtube.com/watch?v=cU3F-xgHI4M',
 'https://www.youtube.com/watch?v=7VSYTyjZW60',
 'https://www.youtube.com/watch?v=nd6921coDhs',
 'https://www.youtube.com/watch?v=TKyauws6QZA',
 'https://www.youtube.com/watch?v=gs_-N3fb4zE',
 'https://www.youtube.com/watch?v=5A0HvbyCOGk',
 'https://www.youtube.com/watch?v=8OgSSIGVZeM',
 'https://www.youtube.com/watch?v=CSvONAOsmac',
 'https://www.youtube.com/watch?v=5bovfm

In [ ]:
# June
vice_urls_lst6 = scrape_urls(channel_id, topic, max_result, start_dates[5], end_dates[5])
vice_urls_lst6

In [163]:
# July
vice_urls_lst7 = scrape_urls(channel_id, topic, max_result, start_dates[6], end_dates[6])
vice_urls_lst7

['https://www.youtube.com/watch?v=iM6E43ixVCo',
 'https://www.youtube.com/watch?v=2sAsFZy526Y',
 'https://www.youtube.com/watch?v=N9SR09eC_z0',
 'https://www.youtube.com/watch?v=omBXPWuyhMI',
 'https://www.youtube.com/watch?v=kqrPQt4PMrM',
 'https://www.youtube.com/watch?v=Y5CnEeqnehc',
 'https://www.youtube.com/watch?v=Fgkf7VGtZfY',
 'https://www.youtube.com/watch?v=Pu2kaJ1eYMU',
 'https://www.youtube.com/watch?v=YodCK0dptRg',
 'https://www.youtube.com/watch?v=Zt4YbW6xdLU',
 'https://www.youtube.com/watch?v=yhiccBZjfXU',
 'https://www.youtube.com/watch?v=V7fiZv8Dkjs',
 'https://www.youtube.com/watch?v=dzAioL3Ji6Q',
 'https://www.youtube.com/watch?v=ff07PqymHpg',
 'https://www.youtube.com/watch?v=hxdwbZ3Oeyc',
 'https://www.youtube.com/watch?v=CditmrwFzDM',
 'https://www.youtube.com/watch?v=_J3nVC0GoVg',
 'https://www.youtube.com/watch?v=46OjTP8X_sc']

In [162]:
# August
vice_urls_lst8 = scrape_urls(channel_id, topic, max_result, start_dates[7], end_dates[7])
vice_urls_lst8

['https://www.youtube.com/watch?v=Imj5EGZzrwg',
 'https://www.youtube.com/watch?v=27OvyWmOr98',
 'https://www.youtube.com/watch?v=Vq6MjpXyxmQ',
 'https://www.youtube.com/watch?v=uaDZ0bVresE',
 'https://www.youtube.com/watch?v=huh1gFTQzM0',
 'https://www.youtube.com/watch?v=rUfMkIx7Ypg',
 'https://www.youtube.com/watch?v=kI-mOg6Ctog',
 'https://www.youtube.com/watch?v=OE3gIqiNKNA',
 'https://www.youtube.com/watch?v=fzcfFkcVcBE',
 'https://www.youtube.com/watch?v=XfmPu8l24wY',
 'https://www.youtube.com/watch?v=NbHAWNQRV70',
 'https://www.youtube.com/watch?v=x_jGPf764d0',
 'https://www.youtube.com/watch?v=JmAqdL9gQLA',
 'https://www.youtube.com/watch?v=Ig5uP2R_9bg',
 'https://www.youtube.com/watch?v=Jnd_xS8l5Ck',
 'https://www.youtube.com/watch?v=MJH7WkfCyco',
 'https://www.youtube.com/watch?v=L62rHDJFAkg',
 'https://www.youtube.com/watch?v=ZvCd-YArC_w']

In [161]:
# September
vice_urls_lst9 = scrape_urls(channel_id, topic, max_result, start_dates[8], end_dates[8])
vice_urls_lst9

['https://www.youtube.com/watch?v=7fJpRa7o_fQ',
 'https://www.youtube.com/watch?v=qX_aaRepdIM',
 'https://www.youtube.com/watch?v=6mOwGAI6_DA',
 'https://www.youtube.com/watch?v=xI2rGqacNy4',
 'https://www.youtube.com/watch?v=FsSUTSgqL3o',
 'https://www.youtube.com/watch?v=1PIMPdFpJVU',
 'https://www.youtube.com/watch?v=5wj2f3ZTK4Y',
 'https://www.youtube.com/watch?v=MuM-HOhAg6w',
 'https://www.youtube.com/watch?v=GQgPYbE6ZIM',
 'https://www.youtube.com/watch?v=4Tr3jCCHlwE',
 'https://www.youtube.com/watch?v=Wuzm1Wz4xmI',
 'https://www.youtube.com/watch?v=ZQUqn14CWzk',
 'https://www.youtube.com/watch?v=ngppWpBKRZE',
 'https://www.youtube.com/watch?v=J1yD2J8vHAk',
 'https://www.youtube.com/watch?v=HL4a1H6foAQ',
 'https://www.youtube.com/watch?v=kkxx9IHAMfw',
 'https://www.youtube.com/watch?v=Ayk_EaON2OY',
 'https://www.youtube.com/watch?v=1_PIB9cEAgE']

In [160]:
# October
vice_urls_lst10 = scrape_urls(channel_id, topic, max_result, start_dates[9], end_dates[9])
vice_urls_lst10

['https://www.youtube.com/watch?v=VOl2-xI76tI',
 'https://www.youtube.com/watch?v=X0Gt34ubpKs',
 'https://www.youtube.com/watch?v=wM9yd1Mf_EM',
 'https://www.youtube.com/watch?v=cdZy4balvB8',
 'https://www.youtube.com/watch?v=PyAbBE7lUwo',
 'https://www.youtube.com/watch?v=ZT3F9ab96II',
 'https://www.youtube.com/watch?v=M4BOdBJFkgA',
 'https://www.youtube.com/watch?v=GJc-YI7OWfY',
 'https://www.youtube.com/watch?v=0hYGo8Pfgow',
 'https://www.youtube.com/watch?v=0cZJHTH8HrM',
 'https://www.youtube.com/watch?v=xnS2CTmdA0A',
 'https://www.youtube.com/watch?v=JemSTLOEXiQ',
 'https://www.youtube.com/watch?v=te7UMbJHsNs',
 'https://www.youtube.com/watch?v=ikneKQAeUp0',
 'https://www.youtube.com/watch?v=UVDt2ZSW1ks',
 'https://www.youtube.com/watch?v=G4Rqhca1ZpU',
 'https://www.youtube.com/watch?v=Xt5G10wm8Z8',
 'https://www.youtube.com/watch?v=1_S2lDPWGuI',
 'https://www.youtube.com/watch?v=d5jK4BzbgXw',
 'https://www.youtube.com/watch?v=xkNrHLSs7dU',
 'https://www.youtube.com/watch?v=nUeSEF

In [144]:
# November
vice_urls_lst11 = scrape_urls(channel_id, topic, max_result, start_dates[10], end_dates[10])
vice_urls_lst11

['https://www.youtube.com/watch?v=_gz36tqn1fw',
 'https://www.youtube.com/watch?v=AHRM_QNvp9E',
 'https://www.youtube.com/watch?v=D-VkWkPs1aw',
 'https://www.youtube.com/watch?v=X03ErYGB4Kk',
 'https://www.youtube.com/watch?v=pn548uALuYw',
 'https://www.youtube.com/watch?v=vU_hwXaX3k0',
 'https://www.youtube.com/watch?v=pcboejDoDz8',
 'https://www.youtube.com/watch?v=1WsonSl8uu8',
 'https://www.youtube.com/watch?v=Rpi4fUZ-Sj4',
 'https://www.youtube.com/watch?v=O9yrM92WwlM',
 'https://www.youtube.com/watch?v=ua3ciaA_a80',
 'https://www.youtube.com/watch?v=cgFLQDbzoZQ',
 'https://www.youtube.com/watch?v=S0apLLG5Ww4',
 'https://www.youtube.com/watch?v=l391-gOsfUs',
 'https://www.youtube.com/watch?v=6DQYu4iBNiQ',
 'https://www.youtube.com/watch?v=MV1WE8-NeuI',
 'https://www.youtube.com/watch?v=mo8WQqvKU1c',
 'https://www.youtube.com/watch?v=Z4GtcMCTm_4',
 'https://www.youtube.com/watch?v=ubnRh3NRJ0w',
 'https://www.youtube.com/watch?v=0hJfVQBS55I',
 'https://www.youtube.com/watch?v=y_YDMb

In [146]:
# December
vice_urls_lst12 = scrape_urls(channel_id, topic, max_result, start_dates[11], '2020-12-31T23:59:59Z')
vice_urls_lst12

['https://www.youtube.com/watch?v=07lsXkWmpz8',
 'https://www.youtube.com/watch?v=2__apjp1hZM',
 'https://www.youtube.com/watch?v=WBdiZy8sxaw',
 'https://www.youtube.com/watch?v=DqiZ0IWbd5k',
 'https://www.youtube.com/watch?v=aNKDNFERkN0',
 'https://www.youtube.com/watch?v=kOHTaAjQs4o',
 'https://www.youtube.com/watch?v=nou51h4OaS8',
 'https://www.youtube.com/watch?v=QfDyc73o2LA',
 'https://www.youtube.com/watch?v=hQDrcGyyanA',
 'https://www.youtube.com/watch?v=gBT02JYWiKA',
 'https://www.youtube.com/watch?v=xYZPrDZHi2o',
 'https://www.youtube.com/watch?v=RjlPEE5J7e0',
 'https://www.youtube.com/watch?v=MiT15PIelbA',
 'https://www.youtube.com/watch?v=_p8y7Cd2-gs',
 'https://www.youtube.com/watch?v=OFq8jyqvlj0',
 'https://www.youtube.com/watch?v=_0ijXUMca54',
 'https://www.youtube.com/watch?v=jGQhEa_0NVU',
 'https://www.youtube.com/watch?v=c7TYyTWKCHI',
 'https://www.youtube.com/watch?v=MdjBTBu8PEk',
 'https://www.youtube.com/watch?v=vmTOMAg8d-c',
 'https://www.youtube.com/watch?v=JyaRfh

In [166]:
vice_yearly_lst = [vice_urls_lst1, vice_urls_lst2,
                         vice_urls_lst3, vice_urls_lst4,
                         vice_urls_lst5,
                         vice_urls_lst7, vice_urls_lst8,
                         vice_urls_lst9, vice_urls_lst10,
                         vice_urls_lst11, vice_urls_lst12]

with open("/Users/itsyuzhou/Autumn2023/MA_thesis/vice_urls.csv", mode='w', newline='') as file:
    writer = csv.writer(file)

    for urls_monthly in vice_yearly_lst:
        for url in urls_monthly:
            writer.writerow([url])
        writer.writerow([])

In [167]:
total_video = 0
month = 0
monthly_videos_counts = []
for url_lst in vice_yearly_lst:
    month += 1
    monthly_videos_counts.append((month, len(url_lst)))

print(monthly_videos_counts)

for (month, monthly_count) in monthly_videos_counts:
    total_video += monthly_count
print("Vice 2020 total video counts=", total_video)

[(1, 9), (2, 0), (3, 21), (4, 29), (5, 24), (6, 18), (7, 18), (8, 18), (9, 27), (10, 26), (11, 23)]
Vice 2020 total video counts= 213


### 2.3 Steve Turley 2020

In [155]:
start_dates, end_dates = generate_start_end_time(2020)
channel_id = SteveTurley_channel_id
topic = 'covid'
max_result = 30

In [108]:
SteveTurley_urls_lst1 = scrape_urls(channel_id, topic, max_result, start_dates[0], end_dates[0])
SteveTurley_urls_lst1

[]

In [109]:
SteveTurley_urls_lst2 = scrape_urls(channel_id, topic, max_result, start_dates[1], end_dates[1])
SteveTurley_urls_lst2

['https://www.youtube.com/watch?v=FXVnF2oKT1U',
 'https://www.youtube.com/watch?v=Ou26PM6y904',
 'https://www.youtube.com/watch?v=HzqpL7BsgNI']

In [110]:
SteveTurley_urls_lst3 = scrape_urls(channel_id, topic, max_result, start_dates[2], end_dates[2])
SteveTurley_urls_lst3

['https://www.youtube.com/watch?v=dZaA-7m_0Ss',
 'https://www.youtube.com/watch?v=-x2wOFitXKE',
 'https://www.youtube.com/watch?v=O1OXOobGo4w',
 'https://www.youtube.com/watch?v=JZWLpmIwKOU',
 'https://www.youtube.com/watch?v=BQx2xsfy5NA',
 'https://www.youtube.com/watch?v=LDL1OcEOgrI',
 'https://www.youtube.com/watch?v=d919-5LGbsY',
 'https://www.youtube.com/watch?v=c7KiPI6kRuA',
 'https://www.youtube.com/watch?v=g3Yx7YOcQk0',
 'https://www.youtube.com/watch?v=BwST6I21fv0',
 'https://www.youtube.com/watch?v=HMnW6Rt1T-E',
 'https://www.youtube.com/watch?v=4kNiZZOnbUg',
 'https://www.youtube.com/watch?v=Uh-OG05ttMY',
 'https://www.youtube.com/watch?v=ETYqHppLOVw']

In [111]:
SteveTurley_urls_lst4 = scrape_urls(channel_id, topic, max_result, start_dates[3], end_dates[3])
SteveTurley_urls_lst4

['https://www.youtube.com/watch?v=MgpTF4SsUB8',
 'https://www.youtube.com/watch?v=Bz7nyVCQL2s',
 'https://www.youtube.com/watch?v=7YOe8A1SvuE',
 'https://www.youtube.com/watch?v=RowPncrGuI0',
 'https://www.youtube.com/watch?v=bHXbievoHng',
 'https://www.youtube.com/watch?v=uWA4IcBQ0YA',
 'https://www.youtube.com/watch?v=9FvJasvzZOo',
 'https://www.youtube.com/watch?v=jV0PGwf1sDk',
 'https://www.youtube.com/watch?v=dFQOzyEctak',
 'https://www.youtube.com/watch?v=zYWBFZvFE1A',
 'https://www.youtube.com/watch?v=tu5v4GfFB40',
 'https://www.youtube.com/watch?v=Bv8FxerAeAQ',
 'https://www.youtube.com/watch?v=e6kpc36vGXQ',
 'https://www.youtube.com/watch?v=OJ9g5qgApAw',
 'https://www.youtube.com/watch?v=VKFeNGeOn08',
 'https://www.youtube.com/watch?v=lNvMkY--7jc',
 'https://www.youtube.com/watch?v=uQMmTe32OGo',
 'https://www.youtube.com/watch?v=Nq56Vbi7bRo',
 'https://www.youtube.com/watch?v=OfZfFESP_RE',
 'https://www.youtube.com/watch?v=rqTunnaOSEM']

In [112]:
SteveTurley_urls_lst5 = scrape_urls(channel_id, topic, max_result, start_dates[4], end_dates[4])
SteveTurley_urls_lst5

['https://www.youtube.com/watch?v=T28UnNydOi0',
 'https://www.youtube.com/watch?v=0jDHojuXAdI',
 'https://www.youtube.com/watch?v=B55cAUGt4Lg',
 'https://www.youtube.com/watch?v=cMBNp9WBsjk',
 'https://www.youtube.com/watch?v=iSGwz4aIhbI',
 'https://www.youtube.com/watch?v=Ts8d8kMdmfM',
 'https://www.youtube.com/watch?v=s6La9rujNBM',
 'https://www.youtube.com/watch?v=PNh8VYc31yU',
 'https://www.youtube.com/watch?v=UF_pLdC5Y-8',
 'https://www.youtube.com/watch?v=DObax4JdxqQ',
 'https://www.youtube.com/watch?v=k-ms7TWsFvo',
 'https://www.youtube.com/watch?v=-ycmuZKrTiA',
 'https://www.youtube.com/watch?v=pWiHOgtqeGM',
 'https://www.youtube.com/watch?v=2QC-XlzwOY0',
 'https://www.youtube.com/watch?v=3p2GGWOJKUw',
 'https://www.youtube.com/watch?v=lxtlu4xgY2Y',
 'https://www.youtube.com/watch?v=hoR-YF84Ie0',
 'https://www.youtube.com/watch?v=dxAGCZkVYAM',
 'https://www.youtube.com/watch?v=tUx5l5hBtDU',
 'https://www.youtube.com/watch?v=1rcbzcJBzGU',
 'https://www.youtube.com/watch?v=CBzJYQ

In [113]:
SteveTurley_urls_lst6 = scrape_urls(channel_id, topic, max_result, start_dates[5], end_dates[5])
SteveTurley_urls_lst6

['https://www.youtube.com/watch?v=cxWpS35wdVU',
 'https://www.youtube.com/watch?v=I6Ydg8ZYcHw',
 'https://www.youtube.com/watch?v=U77UC6FwTh8',
 'https://www.youtube.com/watch?v=PwvmpmJZmcw',
 'https://www.youtube.com/watch?v=GCWTIQOapbc',
 'https://www.youtube.com/watch?v=ukEBAVXGbWs',
 'https://www.youtube.com/watch?v=wGtFNOiLBOo',
 'https://www.youtube.com/watch?v=YlsRhAiApz4',
 'https://www.youtube.com/watch?v=lj3AiiFoyLE',
 'https://www.youtube.com/watch?v=Doo2RC-67M0',
 'https://www.youtube.com/watch?v=MDoiIHrAxeg',
 'https://www.youtube.com/watch?v=E499WMS0Qn0']

In [114]:
SteveTurley_urls_lst7 = scrape_urls(channel_id, topic, max_result, start_dates[6], end_dates[6])
SteveTurley_urls_lst7

['https://www.youtube.com/watch?v=vxvBzIdbtwo',
 'https://www.youtube.com/watch?v=FQv3K2puohc',
 'https://www.youtube.com/watch?v=GJzoJr7oLvc',
 'https://www.youtube.com/watch?v=tg3-c6h-5uQ',
 'https://www.youtube.com/watch?v=NTiGEzAwf28',
 'https://www.youtube.com/watch?v=wxyslfZcl04',
 'https://www.youtube.com/watch?v=cRHF_RNSc4w',
 'https://www.youtube.com/watch?v=gi6ey6b7kCc',
 'https://www.youtube.com/watch?v=pB-EECzwM-g',
 'https://www.youtube.com/watch?v=t-aygtN9tFc',
 'https://www.youtube.com/watch?v=UhOcS8kpu48',
 'https://www.youtube.com/watch?v=TZrtlM-6e3Q']

In [117]:
SteveTurley_urls_lst8 = scrape_urls(channel_id, topic, max_result, start_dates[7], end_dates[7])
SteveTurley_urls_lst8

['https://www.youtube.com/watch?v=l38F2vpAM7o',
 'https://www.youtube.com/watch?v=L-yi2C7RlQQ',
 'https://www.youtube.com/watch?v=uSkJEL6iEoM',
 'https://www.youtube.com/watch?v=wq_tHxSV3zo',
 'https://www.youtube.com/watch?v=qfRCAVFJu9w',
 'https://www.youtube.com/watch?v=4t4Y8MyCbbI',
 'https://www.youtube.com/watch?v=wm9jOhU_qq4',
 'https://www.youtube.com/watch?v=FKPZF7QHvzI',
 'https://www.youtube.com/watch?v=wjWtkIfrd8M',
 'https://www.youtube.com/watch?v=lJmJ8DKoGv8',
 'https://www.youtube.com/watch?v=_QLkkZRGHaI',
 'https://www.youtube.com/watch?v=rxy20MHARcA',
 'https://www.youtube.com/watch?v=aKLQehkeYYA',
 'https://www.youtube.com/watch?v=b7tDW7hA6wM',
 'https://www.youtube.com/watch?v=xZ--M_ai2HE',
 'https://www.youtube.com/watch?v=iENDBgAMnZM']

In [118]:
SteveTurley_urls_lst9 = scrape_urls(channel_id, topic, max_result, start_dates[8], end_dates[8])
SteveTurley_urls_lst9

['https://www.youtube.com/watch?v=kor4-rJTXUY',
 'https://www.youtube.com/watch?v=UsoNuj2TPxk',
 'https://www.youtube.com/watch?v=vMQj15QwlgQ',
 'https://www.youtube.com/watch?v=FEiq0ZMbXwY',
 'https://www.youtube.com/watch?v=tJcxwQGyq5I',
 'https://www.youtube.com/watch?v=mgLHmdJZcjs',
 'https://www.youtube.com/watch?v=tBbWvebr6dA',
 'https://www.youtube.com/watch?v=J13K_0qumZw',
 'https://www.youtube.com/watch?v=qAjvDltPTeg',
 'https://www.youtube.com/watch?v=2a3wnGytT-A',
 'https://www.youtube.com/watch?v=gRNJ_UGxxkU',
 'https://www.youtube.com/watch?v=9Tynfd2JfmY',
 'https://www.youtube.com/watch?v=JkkIVAvedbI',
 'https://www.youtube.com/watch?v=EMJRwgU5pR0',
 'https://www.youtube.com/watch?v=kuXZugmKT38',
 'https://www.youtube.com/watch?v=L3UPKgAijkM',
 'https://www.youtube.com/watch?v=uLZPdHTaGv8',
 'https://www.youtube.com/watch?v=h2am8FsSQEg',
 'https://www.youtube.com/watch?v=RqcCnujLTKs',
 'https://www.youtube.com/watch?v=dbf6Qk73avk',
 'https://www.youtube.com/watch?v=ch3InJ

In [119]:
SteveTurley_urls_lst10 = scrape_urls(channel_id, topic, max_result, start_dates[9], end_dates[9])
SteveTurley_urls_lst10

['https://www.youtube.com/watch?v=1yuoU6kUZJ0',
 'https://www.youtube.com/watch?v=dm_iDMxH52E',
 'https://www.youtube.com/watch?v=pd1kC5bXS8s',
 'https://www.youtube.com/watch?v=Higl6aI9TPM',
 'https://www.youtube.com/watch?v=FzAoL2rYxDE',
 'https://www.youtube.com/watch?v=7HVR7g5HkpA',
 'https://www.youtube.com/watch?v=A6p1b7Xi7ck',
 'https://www.youtube.com/watch?v=YhSUI1D5G7k',
 'https://www.youtube.com/watch?v=9-gDSVGA0GU',
 'https://www.youtube.com/watch?v=1Im0YgeHGiY',
 'https://www.youtube.com/watch?v=TU3U1AUn9kk',
 'https://www.youtube.com/watch?v=-mJjoTKCKoI',
 'https://www.youtube.com/watch?v=E8jsEWRxwkc',
 'https://www.youtube.com/watch?v=DkvTlbM1En0',
 'https://www.youtube.com/watch?v=xc_3d6OElXY',
 'https://www.youtube.com/watch?v=S5YZ_Y5XE5Q',
 'https://www.youtube.com/watch?v=lfSs_QUmAkA',
 'https://www.youtube.com/watch?v=zjAVvJ9Ia_s',
 'https://www.youtube.com/watch?v=XHMgDWROTgY']

In [120]:
SteveTurley_urls_lst11 = scrape_urls(channel_id, topic, max_result, start_dates[10], end_dates[10])
SteveTurley_urls_lst11

['https://www.youtube.com/watch?v=0YH03jBS9NQ',
 'https://www.youtube.com/watch?v=UI8XlLVlYGs',
 'https://www.youtube.com/watch?v=Ixsp1JF_wq0',
 'https://www.youtube.com/watch?v=BpKAUSb8kLQ',
 'https://www.youtube.com/watch?v=JDaAx-HjvpM',
 'https://www.youtube.com/watch?v=wMQ9a2mlsRw',
 'https://www.youtube.com/watch?v=o-jAMeWZmFU',
 'https://www.youtube.com/watch?v=wgm_SJNNG-E',
 'https://www.youtube.com/watch?v=8csentEYaGg',
 'https://www.youtube.com/watch?v=25hMwJ7xo2E',
 'https://www.youtube.com/watch?v=8fFQ_vGuqhM']

In [156]:
SteveTurley_urls_lst12 = scrape_urls(channel_id, topic, max_result, start_dates[11], '2020-12-31T23:59:59Z')
SteveTurley_urls_lst12

['https://www.youtube.com/watch?v=cnJYCGgoVe8',
 'https://www.youtube.com/watch?v=SmK4xe5OjF4',
 'https://www.youtube.com/watch?v=95VtgQlabLQ',
 'https://www.youtube.com/watch?v=o6ydohdyWMo',
 'https://www.youtube.com/watch?v=TvBL4wKLl9w',
 'https://www.youtube.com/watch?v=8sfL0-_DkPs',
 'https://www.youtube.com/watch?v=aZfblRmWDgE',
 'https://www.youtube.com/watch?v=yP-V4qUbilU',
 'https://www.youtube.com/watch?v=jem-MDSEHBI',
 'https://www.youtube.com/watch?v=jv1xOO7lKfg',
 'https://www.youtube.com/watch?v=Y3OxSIjExlI',
 'https://www.youtube.com/watch?v=olbP5M36RUA',
 'https://www.youtube.com/watch?v=LefYqOAoq1g',
 'https://www.youtube.com/watch?v=EiVXxxqxLlY',
 'https://www.youtube.com/watch?v=fLUFmBHLHgY',
 'https://www.youtube.com/watch?v=Pubm-TY8Wzg',
 'https://www.youtube.com/watch?v=cvKmnuS9GKo',
 'https://www.youtube.com/watch?v=EJFZ5Fd52dY',
 'https://www.youtube.com/watch?v=-ILlTDgO9eQ',
 'https://www.youtube.com/watch?v=Cq1juKPmDK4',
 'https://www.youtube.com/watch?v=Y6dypt

In [157]:
steveturley_yearly_lst = [SteveTurley_urls_lst1, SteveTurley_urls_lst2,
                         SteveTurley_urls_lst3, SteveTurley_urls_lst4,
                         SteveTurley_urls_lst5, SteveTurley_urls_lst6,
                         SteveTurley_urls_lst7, SteveTurley_urls_lst8,
                         SteveTurley_urls_lst9, SteveTurley_urls_lst10,
                         SteveTurley_urls_lst11, SteveTurley_urls_lst12]

with open("/Users/itsyuzhou/Autumn2023/MA_thesis/steveturley_urls.csv", mode='w', newline='') as file:
    writer = csv.writer(file)

    for urls_monthly in steveturley_yearly_lst:
        for url in urls_monthly:
            writer.writerow([url])
        writer.writerow([])

In [158]:
total_video = 0
month = 0
monthly_videos_counts = []
for url_lst in steveturley_yearly_lst:
    month += 1
    monthly_videos_counts.append((month, len(url_lst)))

print(monthly_videos_counts)

for (month, monthly_count) in monthly_videos_counts:
    total_video += monthly_count
print("Dr. Steve Turley 2020 total video counts=", total_video)

[(1, 0), (2, 3), (3, 14), (4, 20), (5, 30), (6, 12), (7, 12), (8, 16), (9, 22), (10, 19), (11, 11), (12, 30)]
Dr. Steve Turley 2020 total video counts= 189


### 2.4 Kim Iversen 2020

In [168]:
start_dates, end_dates = generate_start_end_time(2020)
channel_id = KimIversen_channel_id
topic = 'covid'
max_result = 30

In [169]:
kimiversen_urls_lst1 = scrape_urls(channel_id, topic, max_result, start_dates[0], end_dates[0])
kimiversen_urls_lst1

['https://www.youtube.com/watch?v=f5gfZWfqZuI']

In [171]:
kimiversen_urls_lst2 = scrape_urls(channel_id, topic, max_result, start_dates[1], end_dates[1])
kimiversen_urls_lst2

['https://www.youtube.com/watch?v=MI_oN2JloNI']

In [170]:
kimiversen_urls_lst3 = scrape_urls(channel_id, topic, max_result, start_dates[2], end_dates[2])
kimiversen_urls_lst3

['https://www.youtube.com/watch?v=kcvBtjD32QE',
 'https://www.youtube.com/watch?v=lwzB_AZtYOo',
 'https://www.youtube.com/watch?v=ob8jWZaf3XY',
 'https://www.youtube.com/watch?v=aTzMPjLvBl0',
 'https://www.youtube.com/watch?v=qCywEMmVi3Y',
 'https://www.youtube.com/watch?v=hbEUDS_wr8k']

In [172]:
kimiversen_urls_lst4 = scrape_urls(channel_id, topic, max_result, start_dates[3], end_dates[3])
kimiversen_urls_lst4

['https://www.youtube.com/watch?v=HHu2yKG2-V0',
 'https://www.youtube.com/watch?v=JuKbxHHhEC4',
 'https://www.youtube.com/watch?v=tMPujoBkGuk',
 'https://www.youtube.com/watch?v=zvUuoPPkKBM',
 'https://www.youtube.com/watch?v=XY9xApqhze8']

In [173]:
kimiversen_urls_lst5 = scrape_urls(channel_id, topic, max_result, start_dates[4], end_dates[4])
kimiversen_urls_lst5

['https://www.youtube.com/watch?v=ZaP6zrwkOFY',
 'https://www.youtube.com/watch?v=Wsul3AmJVak',
 'https://www.youtube.com/watch?v=hXEpuDCbn_Q']

In [174]:
kimiversen_urls_lst6 = scrape_urls(channel_id, topic, max_result, start_dates[5], end_dates[5])
kimiversen_urls_lst6

['https://www.youtube.com/watch?v=4P_8KtP3Qi0',
 'https://www.youtube.com/watch?v=5aoXHyN_uwM',
 'https://www.youtube.com/watch?v=554ONcKQeA0',
 'https://www.youtube.com/watch?v=i_vtJ4iMKXw']

In [175]:
kimiversen_urls_lst7 = scrape_urls(channel_id, topic, max_result, start_dates[6], end_dates[6])
kimiversen_urls_lst7

['https://www.youtube.com/watch?v=nxq3Y7NKbF0',
 'https://www.youtube.com/watch?v=FpRWVMmR8tE',
 'https://www.youtube.com/watch?v=blD0N2SNtAw',
 'https://www.youtube.com/watch?v=-_o0AE0p7f4']

In [176]:
kimiversen_urls_lst8 = scrape_urls(channel_id, topic, max_result, start_dates[7], end_dates[7])
kimiversen_urls_lst8

['https://www.youtube.com/watch?v=-qVNH-upcPo',
 'https://www.youtube.com/watch?v=7QT7_ZKwm-A',
 'https://www.youtube.com/watch?v=kwQ1ZVsiuHM',
 'https://www.youtube.com/watch?v=ya2arQ94BG8',
 'https://www.youtube.com/watch?v=k6zm2Kf5Yv0']

In [177]:
kimiversen_urls_lst9 = scrape_urls(channel_id, topic, max_result, start_dates[8], end_dates[8])
kimiversen_urls_lst9

['https://www.youtube.com/watch?v=-cv2FStCzG8',
 'https://www.youtube.com/watch?v=SF-BJbAA0vg',
 'https://www.youtube.com/watch?v=7QCqDhlr8UI',
 'https://www.youtube.com/watch?v=0UslhCx3TPM']

In [178]:
kimiversen_urls_lst10 = scrape_urls(channel_id, topic, max_result, start_dates[9], end_dates[9])
kimiversen_urls_lst10

['https://www.youtube.com/watch?v=EovTX9uaoHQ',
 'https://www.youtube.com/watch?v=IbgZ8vgyhwE',
 'https://www.youtube.com/watch?v=ZFTaME_kHoA',
 'https://www.youtube.com/watch?v=UzqniEaXwQg']

In [179]:
kimiversen_urls_lst11 = scrape_urls(channel_id, topic, max_result, start_dates[10], end_dates[10])
kimiversen_urls_lst11

['https://www.youtube.com/watch?v=ptIGxM9kn9g',
 'https://www.youtube.com/watch?v=DL3YXfPze3Y',
 'https://www.youtube.com/watch?v=Z7YuVwwLQHE']

In [180]:
kimiversen_urls_lst12 = scrape_urls(channel_id, topic, max_result, start_dates[11], '2020-12-31T23:59:59Z')
kimiversen_urls_lst12

['https://www.youtube.com/watch?v=PAitD3sgANY',
 'https://www.youtube.com/watch?v=7eaVeANQghg',
 'https://www.youtube.com/watch?v=Kdbtpbf9a9w',
 'https://www.youtube.com/watch?v=zTk2Ng3PjZY']

In [181]:
kimiversen_yearly_lst = [kimiversen_urls_lst1, kimiversen_urls_lst2,
                         kimiversen_urls_lst3, kimiversen_urls_lst4,
                         kimiversen_urls_lst5, kimiversen_urls_lst6,
                         kimiversen_urls_lst7, kimiversen_urls_lst8,
                         kimiversen_urls_lst9, kimiversen_urls_lst10,
                         kimiversen_urls_lst11, kimiversen_urls_lst12]

with open("/Users/itsyuzhou/Autumn2023/MA_thesis/kimiversen_url.csv", mode='w', newline='') as file:
    writer = csv.writer(file)

    for urls_monthly in kimiversen_yearly_lst:
        for url in urls_monthly:
            writer.writerow([url])
        writer.writerow([])

In [182]:
total_video = 0
month = 0
monthly_videos_counts = []
for url_lst in kimiversen_yearly_lst:
    month += 1
    monthly_videos_counts.append((month, len(url_lst)))

print(monthly_videos_counts)

for (month, monthly_count) in monthly_videos_counts:
    total_video += monthly_count
print("Kim Iversen 2020 total video counts=", total_video)

[(1, 1), (2, 1), (3, 6), (4, 5), (5, 3), (6, 4), (7, 4), (8, 5), (9, 4), (10, 4), (11, 3), (12, 4)]
Kim Iversen 2020 total video counts= 44


### 2.5 ABC 2020

In [184]:
start_dates, end_dates = generate_start_end_time(2020)
channel_id = abc_channel_id
topic = 'covid'
max_result = 30

In [185]:
abc_urls_lst1 = scrape_urls(channel_id, topic, max_result, start_dates[0], end_dates[0])
abc_urls_lst1

['https://www.youtube.com/watch?v=FMc280EtXxs',
 'https://www.youtube.com/watch?v=kkSmm7NdHn0',
 'https://www.youtube.com/watch?v=zkds3EnRdIA',
 'https://www.youtube.com/watch?v=ChMwLS4f4HU',
 'https://www.youtube.com/watch?v=q6NsnRVzd8Q',
 'https://www.youtube.com/watch?v=sAbj_fcEL_0',
 'https://www.youtube.com/watch?v=uEIqfLl1VeE',
 'https://www.youtube.com/watch?v=ach1t2Jocy8',
 'https://www.youtube.com/watch?v=vVB1K6ejleI',
 'https://www.youtube.com/watch?v=TCvZjn1uhSU',
 'https://www.youtube.com/watch?v=mfOLZ_TyjlA',
 'https://www.youtube.com/watch?v=L3T-3lvgC18',
 'https://www.youtube.com/watch?v=-S3ED24fbwI',
 'https://www.youtube.com/watch?v=KieB_Zi5TKI',
 'https://www.youtube.com/watch?v=x_pCOdEEuOg',
 'https://www.youtube.com/watch?v=OZppSR3PsKU',
 'https://www.youtube.com/watch?v=Kv5IIOLsC2w',
 'https://www.youtube.com/watch?v=GHcWZiAgbFo',
 'https://www.youtube.com/watch?v=Yj-KpXam8q4',
 'https://www.youtube.com/watch?v=L661YzmPhVw',
 'https://www.youtube.com/watch?v=YpIJrZ

In [187]:
abc_urls_lst2 = scrape_urls(channel_id, topic, max_result, start_dates[1], end_dates[1])
abc_urls_lst2

['https://www.youtube.com/watch?v=3aTarAzzfT4',
 'https://www.youtube.com/watch?v=byU_N9iHBFY',
 'https://www.youtube.com/watch?v=lvLaB6i31SU',
 'https://www.youtube.com/watch?v=Q-CrqxMjiEg',
 'https://www.youtube.com/watch?v=P5nWOdLr0m8',
 'https://www.youtube.com/watch?v=nRnf-mHBrF8',
 'https://www.youtube.com/watch?v=iPqlk9u5oCw',
 'https://www.youtube.com/watch?v=-Foe2zaccoA',
 'https://www.youtube.com/watch?v=dfISBaqnjs0',
 'https://www.youtube.com/watch?v=jwvsgdU-kSw',
 'https://www.youtube.com/watch?v=tICcotTsyXI',
 'https://www.youtube.com/watch?v=T_QWLR1147o',
 'https://www.youtube.com/watch?v=gt5Giokaml0',
 'https://www.youtube.com/watch?v=k7-d-9yX95c',
 'https://www.youtube.com/watch?v=l8Hit_5t-C4',
 'https://www.youtube.com/watch?v=9wYym-SAqKg',
 'https://www.youtube.com/watch?v=Od3oQH3THmI',
 'https://www.youtube.com/watch?v=h-PYpLN5ItM',
 'https://www.youtube.com/watch?v=DNlOnyYivjw',
 'https://www.youtube.com/watch?v=m-EZgWWhp4U',
 'https://www.youtube.com/watch?v=us-432

In [186]:
abc_urls_lst3 = scrape_urls(channel_id, topic, max_result, start_dates[2], end_dates[2])
abc_urls_lst3

['https://www.youtube.com/watch?v=N4WKdZjnU2s',
 'https://www.youtube.com/watch?v=CXOsVXybVJY',
 'https://www.youtube.com/watch?v=bhj0qoKv4ew',
 'https://www.youtube.com/watch?v=9mT0zFR9us8',
 'https://www.youtube.com/watch?v=Qow1al_afYQ',
 'https://www.youtube.com/watch?v=T6bjC8R2pUw',
 'https://www.youtube.com/watch?v=rXyHqMe8JgY',
 'https://www.youtube.com/watch?v=BWb8YqAVTgw',
 'https://www.youtube.com/watch?v=B9JdcKfSpHQ',
 'https://www.youtube.com/watch?v=bIFmh5ujKRw',
 'https://www.youtube.com/watch?v=KovfCPMJU24',
 'https://www.youtube.com/watch?v=yF60WHKSiCM',
 'https://www.youtube.com/watch?v=V-Tk0919M5o',
 'https://www.youtube.com/watch?v=LFnUJX_UB_8',
 'https://www.youtube.com/watch?v=cNomITm-Cr8',
 'https://www.youtube.com/watch?v=KH9ROb67E90',
 'https://www.youtube.com/watch?v=yHjVmwQwszw',
 'https://www.youtube.com/watch?v=PHV4ukogdE0',
 'https://www.youtube.com/watch?v=D9s0Io2geNE',
 'https://www.youtube.com/watch?v=Q6-9_itCNQA',
 'https://www.youtube.com/watch?v=l5twUq

In [188]:
abc_urls_lst4 = scrape_urls(channel_id, topic, max_result, start_dates[3], end_dates[3])
abc_urls_lst4

['https://www.youtube.com/watch?v=nMv1F6BXcEE',
 'https://www.youtube.com/watch?v=RG9WtM1HfBk',
 'https://www.youtube.com/watch?v=SmFmWhO8eY4',
 'https://www.youtube.com/watch?v=lMv3LV0TOqg',
 'https://www.youtube.com/watch?v=obWdv4IiAi4',
 'https://www.youtube.com/watch?v=WaBXQ1irNA0',
 'https://www.youtube.com/watch?v=sgfsi7_n0RU',
 'https://www.youtube.com/watch?v=0P8KyaYuaTg',
 'https://www.youtube.com/watch?v=BSbjCpXBryE',
 'https://www.youtube.com/watch?v=3n8Omo1btSY',
 'https://www.youtube.com/watch?v=bu6KyJyxRbM',
 'https://www.youtube.com/watch?v=jtFVT-LeTLs',
 'https://www.youtube.com/watch?v=xJ6bKaisiNE',
 'https://www.youtube.com/watch?v=r4fFcReN2iM',
 'https://www.youtube.com/watch?v=WIt1NUaSn5U',
 'https://www.youtube.com/watch?v=MmHG87QanEE',
 'https://www.youtube.com/watch?v=smOYWtlkFyc',
 'https://www.youtube.com/watch?v=b2vip71s1x8',
 'https://www.youtube.com/watch?v=h5TRfNAaoSQ',
 'https://www.youtube.com/watch?v=YyqRsOPo4Ik',
 'https://www.youtube.com/watch?v=iaBADz

In [189]:
abc_urls_lst5 = scrape_urls(channel_id, topic, max_result, start_dates[4], end_dates[4])
abc_urls_lst5

['https://www.youtube.com/watch?v=HxGFaWplW9o',
 'https://www.youtube.com/watch?v=m2Wu5IrUkWA',
 'https://www.youtube.com/watch?v=H6FcRe1ymxc',
 'https://www.youtube.com/watch?v=9ppasL1Gym0',
 'https://www.youtube.com/watch?v=G0rDZVgEws8',
 'https://www.youtube.com/watch?v=Kbnf8EXU2TM',
 'https://www.youtube.com/watch?v=8Tyos9E3dpk',
 'https://www.youtube.com/watch?v=P-kfokRqIuA',
 'https://www.youtube.com/watch?v=3BaSbpvdBOo',
 'https://www.youtube.com/watch?v=LShb8o4lS3U',
 'https://www.youtube.com/watch?v=RqYb5siQxnQ',
 'https://www.youtube.com/watch?v=iDO21oqKxdY',
 'https://www.youtube.com/watch?v=yhz6TfgJZhU',
 'https://www.youtube.com/watch?v=WOUczLNNwYM',
 'https://www.youtube.com/watch?v=ScIT_a2jF44',
 'https://www.youtube.com/watch?v=NEWqRcy-6Wg',
 'https://www.youtube.com/watch?v=YihvRKkDHS8',
 'https://www.youtube.com/watch?v=dejUbFMadjI',
 'https://www.youtube.com/watch?v=CS_Y1XCS3Vg',
 'https://www.youtube.com/watch?v=Rj-9mFQd1Nk',
 'https://www.youtube.com/watch?v=FqyrUI

In [190]:
abc_urls_lst6 = scrape_urls(channel_id, topic, max_result, start_dates[5], end_dates[5])
abc_urls_lst6

['https://www.youtube.com/watch?v=YtTJ_ympGMk',
 'https://www.youtube.com/watch?v=qpKt2xM7Z_s',
 'https://www.youtube.com/watch?v=ZPnsuaWT5dE',
 'https://www.youtube.com/watch?v=2vuG8a0lnvM',
 'https://www.youtube.com/watch?v=vhTz9PM1F3E',
 'https://www.youtube.com/watch?v=KLOjH-RSdHQ',
 'https://www.youtube.com/watch?v=Q8nJEcT4w8k',
 'https://www.youtube.com/watch?v=DHRqEqPUc_k',
 'https://www.youtube.com/watch?v=GbbCO1ajMD0',
 'https://www.youtube.com/watch?v=YEVswQCXEgI',
 'https://www.youtube.com/watch?v=5ihUYjScBtk',
 'https://www.youtube.com/watch?v=MARyzTPNgio',
 'https://www.youtube.com/watch?v=T3j0GYe2W5k',
 'https://www.youtube.com/watch?v=K4PJMdNYkUM',
 'https://www.youtube.com/watch?v=mNwEfqTsyCE',
 'https://www.youtube.com/watch?v=Ytke691rGt8',
 'https://www.youtube.com/watch?v=uKtbQ6fewrA',
 'https://www.youtube.com/watch?v=i1Bm6cmY6Ro',
 'https://www.youtube.com/watch?v=1iD0XdpSKxA',
 'https://www.youtube.com/watch?v=tpTAM28Ea0U',
 'https://www.youtube.com/watch?v=P6QWuw

In [191]:
abc_urls_lst7 = scrape_urls(channel_id, topic, max_result, start_dates[6], end_dates[6])
abc_urls_lst7

['https://www.youtube.com/watch?v=WKnKvR2DYZE',
 'https://www.youtube.com/watch?v=L5MLrafV2ik',
 'https://www.youtube.com/watch?v=GbEYfVQ02Wk',
 'https://www.youtube.com/watch?v=-i7BpZEakkY',
 'https://www.youtube.com/watch?v=DvBylNZKe6U',
 'https://www.youtube.com/watch?v=KJHHqWEOzGw',
 'https://www.youtube.com/watch?v=HmDKB0tMC-g',
 'https://www.youtube.com/watch?v=Z3qSktcXTYE',
 'https://www.youtube.com/watch?v=3LmY4p5kPUQ',
 'https://www.youtube.com/watch?v=hsr_4diyjfk',
 'https://www.youtube.com/watch?v=oW8KbRGUsIs',
 'https://www.youtube.com/watch?v=iYJrd5_wQUk',
 'https://www.youtube.com/watch?v=Cf0fuM5rWXM',
 'https://www.youtube.com/watch?v=w5pmWtXF55o',
 'https://www.youtube.com/watch?v=irLJ2YgeIyU',
 'https://www.youtube.com/watch?v=2WUDswbwafA',
 'https://www.youtube.com/watch?v=1yNUS_Me43E',
 'https://www.youtube.com/watch?v=30ZNTo8foyY',
 'https://www.youtube.com/watch?v=BHYV76v7Owk',
 'https://www.youtube.com/watch?v=AkE-q5-Gqu0',
 'https://www.youtube.com/watch?v=W_R0L6

In [192]:
abc_urls_lst8 = scrape_urls(channel_id, topic, max_result, start_dates[7], end_dates[7])
abc_urls_lst8

['https://www.youtube.com/watch?v=Vn2zyo7eduE',
 'https://www.youtube.com/watch?v=F1IurSdJhug',
 'https://www.youtube.com/watch?v=8r3mUR5wgik',
 'https://www.youtube.com/watch?v=CDM5ARRQgrU',
 'https://www.youtube.com/watch?v=Pb76k9I_--I',
 'https://www.youtube.com/watch?v=5RqlcGgwN8E',
 'https://www.youtube.com/watch?v=ve-3Pt1ecmk',
 'https://www.youtube.com/watch?v=jrpbTJHfVUg',
 'https://www.youtube.com/watch?v=so0ThdynGQo',
 'https://www.youtube.com/watch?v=khrHs98DBd0',
 'https://www.youtube.com/watch?v=i0EXw2Rmz8c',
 'https://www.youtube.com/watch?v=ShoA2trlI58',
 'https://www.youtube.com/watch?v=ZRsfgdnIg1Y',
 'https://www.youtube.com/watch?v=0hiNCvzegSs',
 'https://www.youtube.com/watch?v=XfunTHQjwkA',
 'https://www.youtube.com/watch?v=g6aExAenMs4',
 'https://www.youtube.com/watch?v=vGJtJ6RPgHA',
 'https://www.youtube.com/watch?v=-LZoSyHJHfk',
 'https://www.youtube.com/watch?v=F56RBUercfI',
 'https://www.youtube.com/watch?v=qWvY2KfIVe8',
 'https://www.youtube.com/watch?v=wEeWJZ

In [193]:
abc_urls_lst9 = scrape_urls(channel_id, topic, max_result, start_dates[8], end_dates[8])
abc_urls_lst9

['https://www.youtube.com/watch?v=g-R7G1lXho0',
 'https://www.youtube.com/watch?v=0IBU9-9FGeo',
 'https://www.youtube.com/watch?v=RW5ufk4oak8',
 'https://www.youtube.com/watch?v=5zG6f5VynVo',
 'https://www.youtube.com/watch?v=rls6Qy7y9CE',
 'https://www.youtube.com/watch?v=HuKvloC0WJE',
 'https://www.youtube.com/watch?v=97zsLVrinEA',
 'https://www.youtube.com/watch?v=atN3A3a6IfU',
 'https://www.youtube.com/watch?v=lI672O5dGXE',
 'https://www.youtube.com/watch?v=BQWg5_159C4',
 'https://www.youtube.com/watch?v=Ltib33k90wo',
 'https://www.youtube.com/watch?v=pfJgH48nnyM',
 'https://www.youtube.com/watch?v=0AY-0apDj4w',
 'https://www.youtube.com/watch?v=TWVLMmqatec',
 'https://www.youtube.com/watch?v=N4LvC0Bdivs',
 'https://www.youtube.com/watch?v=CUD6CM-C8ik',
 'https://www.youtube.com/watch?v=BvDxxC_rF14',
 'https://www.youtube.com/watch?v=y5mNZz8bWgk',
 'https://www.youtube.com/watch?v=_HYf4njbrMA',
 'https://www.youtube.com/watch?v=gf-JY41sVCc',
 'https://www.youtube.com/watch?v=SRhzmJ

In [194]:
abc_urls_lst10 = scrape_urls(channel_id, topic, max_result, start_dates[9], end_dates[9])
abc_urls_lst10

['https://www.youtube.com/watch?v=QSAK_SdfnIs',
 'https://www.youtube.com/watch?v=tm4ux1i02TA',
 'https://www.youtube.com/watch?v=f-XhAjKRaJA',
 'https://www.youtube.com/watch?v=Od1faToPYaU',
 'https://www.youtube.com/watch?v=f3QM-u-vQ_s',
 'https://www.youtube.com/watch?v=Ou7m-aCsVKs',
 'https://www.youtube.com/watch?v=6WKKx4uZVAY',
 'https://www.youtube.com/watch?v=X6rRtTzMsBo',
 'https://www.youtube.com/watch?v=Nr1my97BkQ4',
 'https://www.youtube.com/watch?v=4UVnUCwANas',
 'https://www.youtube.com/watch?v=_WMmkxg-Y34',
 'https://www.youtube.com/watch?v=4u4kez2KRKM',
 'https://www.youtube.com/watch?v=TBHot3bYByQ',
 'https://www.youtube.com/watch?v=1PiKiZeBzGQ',
 'https://www.youtube.com/watch?v=0BSy4xWwf6Y',
 'https://www.youtube.com/watch?v=5gHehjiX1-8',
 'https://www.youtube.com/watch?v=vrcWEUQXIIg',
 'https://www.youtube.com/watch?v=ysrSMfN0BCI',
 'https://www.youtube.com/watch?v=NwNsWxW04JU',
 'https://www.youtube.com/watch?v=jmSsVixS4uE',
 'https://www.youtube.com/watch?v=wOx9Qd

In [195]:
abc_urls_lst11 = scrape_urls(channel_id, topic, max_result, start_dates[10], end_dates[10])
abc_urls_lst11

['https://www.youtube.com/watch?v=8xh63KUg1LI',
 'https://www.youtube.com/watch?v=8k6G1g7Wpig',
 'https://www.youtube.com/watch?v=WP6U9vqFFYM',
 'https://www.youtube.com/watch?v=IRitvknVnWs',
 'https://www.youtube.com/watch?v=CbVC2yUKVeo',
 'https://www.youtube.com/watch?v=qYfEvNEBBIs',
 'https://www.youtube.com/watch?v=lWo14PEvzc0',
 'https://www.youtube.com/watch?v=ZNw2C5nco58',
 'https://www.youtube.com/watch?v=nibILRsHGQ0',
 'https://www.youtube.com/watch?v=Z-DJWv74A-4',
 'https://www.youtube.com/watch?v=XEbw6k9oZDU',
 'https://www.youtube.com/watch?v=VZmBnFsFhks',
 'https://www.youtube.com/watch?v=O_QxAnDiH-Q',
 'https://www.youtube.com/watch?v=QQ5kzQ7UWQo',
 'https://www.youtube.com/watch?v=-BWlxdPr_9k',
 'https://www.youtube.com/watch?v=4UZC-WfOHyk',
 'https://www.youtube.com/watch?v=pmmu5S-qrL4',
 'https://www.youtube.com/watch?v=g1PFqFVbBfQ',
 'https://www.youtube.com/watch?v=3eqO7wOlnoM',
 'https://www.youtube.com/watch?v=Dsm-mkDiX9s',
 'https://www.youtube.com/watch?v=ECTlNS

In [196]:
abc_urls_lst12 = scrape_urls(channel_id, topic, max_result, start_dates[11], '2020-12-31T23:59:59Z')
abc_urls_lst12

['https://www.youtube.com/watch?v=yg8cp55xaNY',
 'https://www.youtube.com/watch?v=KQQZARNN2RY',
 'https://www.youtube.com/watch?v=_p_gmP_rruw',
 'https://www.youtube.com/watch?v=gTU-_A1qDRI',
 'https://www.youtube.com/watch?v=Kp5bmklhPI0',
 'https://www.youtube.com/watch?v=nwwwqre28EQ',
 'https://www.youtube.com/watch?v=xoALCj0Kw6o',
 'https://www.youtube.com/watch?v=fdtyZI2x4ws',
 'https://www.youtube.com/watch?v=bK4IETp8V3w',
 'https://www.youtube.com/watch?v=qNiyvJbRGZs',
 'https://www.youtube.com/watch?v=WrmdYOuaY20',
 'https://www.youtube.com/watch?v=nlF13YEDL2U',
 'https://www.youtube.com/watch?v=aEx2g5G57KE',
 'https://www.youtube.com/watch?v=YWBwthfI0ao',
 'https://www.youtube.com/watch?v=wmVg_8wUS9s',
 'https://www.youtube.com/watch?v=ekD0QPdqt4c',
 'https://www.youtube.com/watch?v=vpva8PwSHmo',
 'https://www.youtube.com/watch?v=tJF19BbFghI',
 'https://www.youtube.com/watch?v=QnJcBp7657E',
 'https://www.youtube.com/watch?v=Ynb2kZ9AvZM',
 'https://www.youtube.com/watch?v=BJ2rT7

In [197]:
abc_yearly_lst = [abc_urls_lst1, abc_urls_lst2,
                abc_urls_lst3, abc_urls_lst4,
                abc_urls_lst5, abc_urls_lst6,
                abc_urls_lst7, abc_urls_lst8,
                abc_urls_lst9, abc_urls_lst10,
                abc_urls_lst11, abc_urls_lst12]

with open("/Users/itsyuzhou/Autumn2023/MA_thesis/abc_url.csv", mode='w', newline='') as file:
    writer = csv.writer(file)

    for urls_monthly in abc_yearly_lst:
        for url in urls_monthly:
            writer.writerow([url])
        writer.writerow([])

In [198]:
total_video = 0
month = 0
monthly_videos_counts = []
for url_lst in abc_yearly_lst:
    month += 1
    monthly_videos_counts.append((month, len(url_lst)))

print(monthly_videos_counts)

for (month, monthly_count) in monthly_videos_counts:
    total_video += monthly_count
print("ABC news 2020 total video counts=", total_video)

[(1, 23), (2, 30), (3, 30), (4, 30), (5, 30), (6, 30), (7, 30), (8, 30), (9, 30), (10, 30), (11, 30), (12, 30)]
ABC news 2020 total video counts= 353


### 2.6 Robert Reich 2020

In [199]:
start_dates, end_dates = generate_start_end_time(2020)
channel_id = RobertReich_channel_id
topic = 'covid'
max_result = 30

In [200]:
RobertReich_urls_lst1 = scrape_urls(channel_id, topic, max_result, start_dates[0], end_dates[0])
RobertReich_urls_lst1

['https://www.youtube.com/watch?v=_2kW5K-KhvA']

In [201]:
RobertReich_urls_lst2 = scrape_urls(channel_id, topic, max_result, start_dates[1], end_dates[1])
RobertReich_urls_lst2

['https://www.youtube.com/watch?v=n1GKWFZyLbg',
 'https://www.youtube.com/watch?v=LLkq-M_b1wY',
 'https://www.youtube.com/watch?v=90zIplv4BbE']

In [202]:
RobertReich_urls_lst3 = scrape_urls(channel_id, topic, max_result, start_dates[2], end_dates[2])
RobertReich_urls_lst3

['https://www.youtube.com/watch?v=bTRX76Vo3V4',
 'https://www.youtube.com/watch?v=JQPdNYQjyZQ',
 'https://www.youtube.com/watch?v=cTZKyPqBG8U',
 'https://www.youtube.com/watch?v=7UB7U9_uwzQ',
 'https://www.youtube.com/watch?v=3UodmPsGQVE',
 'https://www.youtube.com/watch?v=JytJ8lf8aOQ',
 'https://www.youtube.com/watch?v=Y_sjfchNsiM',
 'https://www.youtube.com/watch?v=szdbnhYP7Y4',
 'https://www.youtube.com/watch?v=z18fQ5TGblY']

In [203]:
RobertReich_urls_lst4 = scrape_urls(channel_id, topic, max_result, start_dates[3], end_dates[3])
RobertReich_urls_lst4

['https://www.youtube.com/watch?v=x6M6c_4YgyA',
 'https://www.youtube.com/watch?v=OPmODosQCQE',
 'https://www.youtube.com/watch?v=5inRUswmMUg',
 'https://www.youtube.com/watch?v=0c9iaM18r8Y',
 'https://www.youtube.com/watch?v=auAM3tjTP5s',
 'https://www.youtube.com/watch?v=en8zzHcVwvg',
 'https://www.youtube.com/watch?v=9AfPh7l09s0',
 'https://www.youtube.com/watch?v=_56cofRjsI4',
 'https://www.youtube.com/watch?v=Op5DXZ6NRzQ',
 'https://www.youtube.com/watch?v=xLjrrhG3tvQ',
 'https://www.youtube.com/watch?v=arnrfevye2k',
 'https://www.youtube.com/watch?v=wuXURo0FUjM',
 'https://www.youtube.com/watch?v=eQELzGkk3jE',
 'https://www.youtube.com/watch?v=jBOVBQpF5DU',
 'https://www.youtube.com/watch?v=_ai840ztGCs',
 'https://www.youtube.com/watch?v=n_lnnUJTt88',
 'https://www.youtube.com/watch?v=PI2phM7eCVU',
 'https://www.youtube.com/watch?v=olAQDUCSJZk']

In [204]:
RobertReich_urls_lst5 = scrape_urls(channel_id, topic, max_result, start_dates[4], end_dates[4])
RobertReich_urls_lst5

['https://www.youtube.com/watch?v=nulcmxH9FGg',
 'https://www.youtube.com/watch?v=kzHT-LKK2xY',
 'https://www.youtube.com/watch?v=jEG8O99PicY',
 'https://www.youtube.com/watch?v=3jU7xQ9C6fE',
 'https://www.youtube.com/watch?v=CxYQWOT7iwo',
 'https://www.youtube.com/watch?v=6W5glARcTNQ',
 'https://www.youtube.com/watch?v=j4Fiutk1S2o',
 'https://www.youtube.com/watch?v=2ypEfj8ifYs',
 'https://www.youtube.com/watch?v=P0Fg8AP_UAI',
 'https://www.youtube.com/watch?v=lCE4FMv1-ho']

In [205]:
RobertReich_urls_lst6 = scrape_urls(channel_id, topic, max_result, start_dates[5], end_dates[5])
RobertReich_urls_lst6

['https://www.youtube.com/watch?v=xbE8gfoYrec',
 'https://www.youtube.com/watch?v=zOUryJO8y_w',
 'https://www.youtube.com/watch?v=MebLiPceEE8',
 'https://www.youtube.com/watch?v=42yF_ydXMXY',
 'https://www.youtube.com/watch?v=rKXzS19Cj3U',
 'https://www.youtube.com/watch?v=oJ50QAkKyxg',
 'https://www.youtube.com/watch?v=HD2BhCjbId0']

In [206]:
RobertReich_urls_lst7 = scrape_urls(channel_id, topic, max_result, start_dates[6], end_dates[6])
RobertReich_urls_lst7

['https://www.youtube.com/watch?v=qTN7Q6neQBM',
 'https://www.youtube.com/watch?v=zr-dw5u1zpQ',
 'https://www.youtube.com/watch?v=KRnkgLHzHb0',
 'https://www.youtube.com/watch?v=IByPiMS5IHg',
 'https://www.youtube.com/watch?v=OcWxZvZD58Q',
 'https://www.youtube.com/watch?v=hwyvjvZO5Ls',
 'https://www.youtube.com/watch?v=2vfl6XTapYc']

In [207]:
RobertReich_urls_lst8 = scrape_urls(channel_id, topic, max_result, start_dates[7], end_dates[7])
RobertReich_urls_lst8

['https://www.youtube.com/watch?v=ushbdoDLen4',
 'https://www.youtube.com/watch?v=nR2gqwi2-Qo',
 'https://www.youtube.com/watch?v=1lkC7siclDc',
 'https://www.youtube.com/watch?v=Yky9xGsjQTE',
 'https://www.youtube.com/watch?v=14p0PpDaqR4',
 'https://www.youtube.com/watch?v=hT0oIWTPW9I',
 'https://www.youtube.com/watch?v=bNkqVfDgzhE',
 'https://www.youtube.com/watch?v=ZT7TfiWuCko',
 'https://www.youtube.com/watch?v=fudqd2lfjQc',
 'https://www.youtube.com/watch?v=HZosrC--Aeg',
 'https://www.youtube.com/watch?v=S3IktCW1XNo']

In [208]:
RobertReich_urls_lst9 = scrape_urls(channel_id, topic, max_result, start_dates[8], end_dates[8])
RobertReich_urls_lst9

['https://www.youtube.com/watch?v=05pwqZ40pzE',
 'https://www.youtube.com/watch?v=ysy4R6LskKo',
 'https://www.youtube.com/watch?v=60PQfYzEoyc',
 'https://www.youtube.com/watch?v=puIXXeALLNc',
 'https://www.youtube.com/watch?v=9vgPe_xBbAo',
 'https://www.youtube.com/watch?v=JNXqySggU_w']

In [209]:
RobertReich_urls_lst10 = scrape_urls(channel_id, topic, max_result, start_dates[9], end_dates[9])
RobertReich_urls_lst10

['https://www.youtube.com/watch?v=0W2L1rMhrAg',
 'https://www.youtube.com/watch?v=VIKLGReBsfE',
 'https://www.youtube.com/watch?v=VElPVcAMYZg',
 'https://www.youtube.com/watch?v=2DYtzzJaUlM',
 'https://www.youtube.com/watch?v=b0wrZVDrNOE']

In [210]:
RobertReich_urls_lst11 = scrape_urls(channel_id, topic, max_result, start_dates[10], end_dates[10])
RobertReich_urls_lst11

['https://www.youtube.com/watch?v=LUpTqFlrwwY']

In [211]:
RobertReich_urls_lst12 = scrape_urls(channel_id, topic, max_result, start_dates[11], '2020-12-31T23:59:59Z')
RobertReich_urls_lst12

['https://www.youtube.com/watch?v=P7oS6UkhAZ4',
 'https://www.youtube.com/watch?v=0VzMKLFEOR0',
 'https://www.youtube.com/watch?v=R6F0jcpJxy0']

In [212]:
RobertReich_yearly_lst = [RobertReich_urls_lst1, RobertReich_urls_lst2,
                        RobertReich_urls_lst3, RobertReich_urls_lst4,
                        RobertReich_urls_lst5, RobertReich_urls_lst6,
                        RobertReich_urls_lst7, RobertReich_urls_lst8,
                        RobertReich_urls_lst9, RobertReich_urls_lst10,
                        RobertReich_urls_lst11, RobertReich_urls_lst12]

with open("/Users/itsyuzhou/Autumn2023/MA_thesis/robertreich_url.csv", mode='w', newline='') as file:
    writer = csv.writer(file)

    for urls_monthly in RobertReich_yearly_lst:
        for url in urls_monthly:
            writer.writerow([url])
        writer.writerow([])

In [213]:
total_video = 0
month = 0
monthly_videos_counts = []
for url_lst in RobertReich_yearly_lst:
    month += 1
    monthly_videos_counts.append((month, len(url_lst)))

print(monthly_videos_counts)

for (month, monthly_count) in monthly_videos_counts:
    total_video += monthly_count
print("Robert Reich 2020 total video counts=", total_video)

[(1, 1), (2, 3), (3, 9), (4, 18), (5, 10), (6, 7), (7, 7), (8, 11), (9, 6), (10, 5), (11, 1), (12, 3)]
Robert Reich 2020 total video counts= 81


### 2.7 VOX 2020

In [217]:
start_dates, end_dates = generate_start_end_time(2020)
topic = 'covid'
max_result = 30

In [222]:
vox_urls_lst1 = scrape_urls(vox_channel_id, topic, max_result, start_dates[0], end_dates[0])
vox_urls_lst1

['https://www.youtube.com/watch?v=qtzvIBAYP_8',
 'https://www.youtube.com/watch?v=EidKI1Bdons']

In [223]:
vox_urls_lst2 = scrape_urls(vox_channel_id, topic, max_result, start_dates[1], end_dates[1])
vox_urls_lst2

['https://www.youtube.com/watch?v=dmWL0I3oytw',
 'https://www.youtube.com/watch?v=4c5fuOPCeYw']

In [224]:
vox_urls_lst3 = scrape_urls(vox_channel_id, topic, max_result, start_dates[2], end_dates[2])
vox_urls_lst3

['https://www.youtube.com/watch?v=TPpoJGYlW54',
 'https://www.youtube.com/watch?v=-LKVUarhtvE',
 'https://www.youtube.com/watch?v=dSQztKXR6k0',
 'https://www.youtube.com/watch?v=xdw7WEMe9AI',
 'https://www.youtube.com/watch?v=QyMusotiUAs',
 'https://www.youtube.com/watch?v=h9d86ocFlxE']

In [225]:
vox_urls_lst4 = scrape_urls(vox_channel_id, topic, max_result, start_dates[3], end_dates[3])
vox_urls_lst4

['https://www.youtube.com/watch?v=421fmflQX0E',
 'https://www.youtube.com/watch?v=FVIGhz3uwuQ',
 'https://www.youtube.com/watch?v=O-3Mlj3MQ_Q',
 'https://www.youtube.com/watch?v=BE-cA4UK07c',
 'https://www.youtube.com/watch?v=P27HRClMf2U',
 'https://www.youtube.com/watch?v=_CrbHvbvvMw',
 'https://www.youtube.com/watch?v=o1iYSsFqVG4']

In [226]:
vox_urls_lst5 = scrape_urls(vox_channel_id, topic, max_result, start_dates[4], end_dates[4])
vox_urls_lst5

['https://www.youtube.com/watch?v=n6QwnzbRUyA',
 'https://www.youtube.com/watch?v=r6ewlQs8CAQ',
 'https://www.youtube.com/watch?v=jLbJayQygzw',
 'https://www.youtube.com/watch?v=XAFD-0aMkwE',
 'https://www.youtube.com/watch?v=HaraFkhonFo',
 'https://www.youtube.com/watch?v=j05xm-8_wjc',
 'https://www.youtube.com/watch?v=I6biQ_2RK3k',
 'https://www.youtube.com/watch?v=qWIVSmx0zPE']

In [227]:
vox_urls_lst6 = scrape_urls(vox_channel_id, topic, max_result, start_dates[5], end_dates[5])
vox_urls_lst6

['https://www.youtube.com/watch?v=2qdd7kirwIk',
 'https://www.youtube.com/watch?v=9Em0FSsI_VU',
 'https://www.youtube.com/watch?v=uWYTaXWO2t0',
 'https://www.youtube.com/watch?v=ualUPur6iks',
 'https://www.youtube.com/watch?v=yw8a8n7ZAZg',
 'https://www.youtube.com/watch?v=Vo61TiAGwhk',
 'https://www.youtube.com/watch?v=hHHCrf2-x6w',
 'https://www.youtube.com/watch?v=srnA3cNTsXQ',
 'https://www.youtube.com/watch?v=6FX-Iisvrj8',
 'https://www.youtube.com/watch?v=HLxvq_M4218']

In [228]:
vox_urls_lst7 = scrape_urls(vox_channel_id, topic, max_result, start_dates[6], end_dates[6])
vox_urls_lst7

['https://www.youtube.com/watch?v=qp5CEcIyk94',
 'https://www.youtube.com/watch?v=2wVPyiyukQc',
 'https://www.youtube.com/watch?v=0EIFDSb7tWc']

In [229]:
vox_urls_lst8 = scrape_urls(vox_channel_id, topic, max_result, start_dates[7], end_dates[7])
vox_urls_lst8

['https://www.youtube.com/watch?v=Djy3WNLz_mM',
 'https://www.youtube.com/watch?v=r2fxJI_cP58',
 'https://www.youtube.com/watch?v=Za6JtPhscxE',
 'https://www.youtube.com/watch?v=hwuujiHvduc',
 'https://www.youtube.com/watch?v=BAsXGN2OX0c']

In [230]:
vox_urls_lst9 = scrape_urls(vox_channel_id, topic, max_result, start_dates[8], end_dates[8])
vox_urls_lst9

['https://www.youtube.com/watch?v=-S_f-huz-EU',
 'https://www.youtube.com/watch?v=exUNdTmmSfs',
 'https://www.youtube.com/watch?v=QfAXbGInwno',
 'https://www.youtube.com/watch?v=_cj_8_upaVo',
 'https://www.youtube.com/watch?v=1Veo_T4a5dM',
 'https://www.youtube.com/watch?v=Bzuk13Ftxgo',
 'https://www.youtube.com/watch?v=wFpfYTYupKA',
 'https://www.youtube.com/watch?v=Y5_37k9HdJw']

In [231]:
vox_urls_lst10 = scrape_urls(vox_channel_id, topic, max_result, start_dates[9], end_dates[9])
vox_urls_lst10

['https://www.youtube.com/watch?v=XB-X2NH0rec',
 'https://www.youtube.com/watch?v=_7FWr2Nvf9I',
 'https://www.youtube.com/watch?v=xRnpUptf7E0',
 'https://www.youtube.com/watch?v=1kBQ0qlHz8M']

In [232]:
vox_urls_lst11 = scrape_urls(vox_channel_id, topic, max_result, start_dates[10], end_dates[10])
vox_urls_lst11

['https://www.youtube.com/watch?v=FoTE-6wWxXs',
 'https://www.youtube.com/watch?v=F07yTI0J3Qk',
 'https://www.youtube.com/watch?v=S4ugBZmctKA',
 'https://www.youtube.com/watch?v=To8PwGTMBoY',
 'https://www.youtube.com/watch?v=NDQ_grwwgtM',
 'https://www.youtube.com/watch?v=4Rnb0j-bNmM']

In [233]:
vox_urls_lst12 = scrape_urls(vox_channel_id, topic, max_result, start_dates[11], '2020-12-31T23:59:59Z')
vox_urls_lst12

['https://www.youtube.com/watch?v=vGQQbulRUjY',
 'https://www.youtube.com/watch?v=Dy5vHFyqY-Y',
 'https://www.youtube.com/watch?v=iHpZV7ro7lU']

In [234]:
vox_yearly_lst = [vox_urls_lst1, vox_urls_lst2,
                vox_urls_lst3, vox_urls_lst4,
                vox_urls_lst5, vox_urls_lst6,
                vox_urls_lst7, vox_urls_lst8,
                vox_urls_lst9, vox_urls_lst10,
                vox_urls_lst11, vox_urls_lst12]

with open("/Users/itsyuzhou/Autumn2023/MA_thesis/vox_url.csv", mode='w', newline='') as file:
    writer = csv.writer(file)

    for urls_monthly in vox_yearly_lst:
        for url in urls_monthly:
            writer.writerow([url])
        writer.writerow([])

In [235]:
total_video = 0
month = 0
monthly_videos_counts = []
for url_lst in vox_yearly_lst:
    month += 1
    monthly_videos_counts.append((month, len(url_lst)))

print(monthly_videos_counts)

for (month, monthly_count) in monthly_videos_counts:
    total_video += monthly_count
print("Vox 2020 total video counts=", total_video)

[(1, 2), (2, 2), (3, 6), (4, 7), (5, 8), (6, 10), (7, 3), (8, 5), (9, 8), (10, 4), (11, 6), (12, 3)]
Vox 2020 total video counts= 64


Stop Asian Hate:
- Start date: March 13, 2021
- Caused by: Killing of Vicha Ratanapakdee; 2021 Atlanta spa shootings; Xenophobia and racism related to the COVID-19 pandemic

## 3. Scrape 2021 Video Links

In [236]:
start_dates, end_dates = generate_start_end_time(2021)
topic = 'covid'
max_result = 30

### 3.1 FOX 2021

In [239]:
fox_urls_202101 = scrape_urls(fox_channel_id, topic, max_result, start_dates[0], end_dates[0])
fox_urls_202101

['https://www.youtube.com/watch?v=nlmy_Pghobo',
 'https://www.youtube.com/watch?v=ry9fKo-f9CI',
 'https://www.youtube.com/watch?v=Qg_ewncrCgk',
 'https://www.youtube.com/watch?v=zSb2ORMmW4g',
 'https://www.youtube.com/watch?v=AAhQa4G8gs0',
 'https://www.youtube.com/watch?v=Q-wquScapCM',
 'https://www.youtube.com/watch?v=dObbstXFFv4',
 'https://www.youtube.com/watch?v=vjyW66p2FwE',
 'https://www.youtube.com/watch?v=lXfbixkBn7M',
 'https://www.youtube.com/watch?v=7GkGLkgyHYw',
 'https://www.youtube.com/watch?v=hH2MXlrF0dE',
 'https://www.youtube.com/watch?v=XC6YKutIgUA',
 'https://www.youtube.com/watch?v=waj_MLVaqJs',
 'https://www.youtube.com/watch?v=FqQ2IZpeK8c',
 'https://www.youtube.com/watch?v=Z1AoLxi2ZD0',
 'https://www.youtube.com/watch?v=syzhk67ye6Q',
 'https://www.youtube.com/watch?v=FNs0cVrxhSs',
 'https://www.youtube.com/watch?v=igq5zMzJ_t4',
 'https://www.youtube.com/watch?v=3XNnboHes3E',
 'https://www.youtube.com/watch?v=Wif4phkPTe0',
 'https://www.youtube.com/watch?v=jEhdl3

In [240]:
fox_urls_202102 = scrape_urls(fox_channel_id, topic, max_result, start_dates[1], end_dates[1])
fox_urls_202102

['https://www.youtube.com/watch?v=Y8UXRKhiDQY',
 'https://www.youtube.com/watch?v=MjqQv5qnt6c',
 'https://www.youtube.com/watch?v=K0OWqZWV3E4',
 'https://www.youtube.com/watch?v=2kK-lDe2uL8',
 'https://www.youtube.com/watch?v=tOVguhCVdUA',
 'https://www.youtube.com/watch?v=ocFPWD1fK9M',
 'https://www.youtube.com/watch?v=dX7FIeeArBM',
 'https://www.youtube.com/watch?v=brvmgsyBuE8',
 'https://www.youtube.com/watch?v=_UoPgqXXovI',
 'https://www.youtube.com/watch?v=R3rTUPG4kXU',
 'https://www.youtube.com/watch?v=QNOMb8qBpK8',
 'https://www.youtube.com/watch?v=GBDX_Ja-3kE',
 'https://www.youtube.com/watch?v=2K95b2cCy_8',
 'https://www.youtube.com/watch?v=6Amb1Rd9q1g',
 'https://www.youtube.com/watch?v=PPtNJRb2Xt8',
 'https://www.youtube.com/watch?v=8HMKHYKCMfE',
 'https://www.youtube.com/watch?v=WsSv2OO0k9A',
 'https://www.youtube.com/watch?v=dx45PHkWVhs',
 'https://www.youtube.com/watch?v=nD3zuvlDevU',
 'https://www.youtube.com/watch?v=51bByx1hTDM',
 'https://www.youtube.com/watch?v=ybqved

In [241]:
fox_urls_202103 = scrape_urls(fox_channel_id, topic, max_result, start_dates[2], end_dates[2])
fox_urls_202103

['https://www.youtube.com/watch?v=y8FkSVH1q2M',
 'https://www.youtube.com/watch?v=ZtQ-goeYY8s',
 'https://www.youtube.com/watch?v=2KodaBf4wWg',
 'https://www.youtube.com/watch?v=XOuvaIB59ys',
 'https://www.youtube.com/watch?v=UcgkOEU57Fc',
 'https://www.youtube.com/watch?v=t0ZhS7amFBs',
 'https://www.youtube.com/watch?v=SzKH3COaBi8',
 'https://www.youtube.com/watch?v=_d43Jyy8HWc',
 'https://www.youtube.com/watch?v=hQ3O05fI2wQ',
 'https://www.youtube.com/watch?v=6ZQTBBntCeA',
 'https://www.youtube.com/watch?v=mPGn66r7at8',
 'https://www.youtube.com/watch?v=D27xFXsjtKs',
 'https://www.youtube.com/watch?v=oryOLS6MXeg',
 'https://www.youtube.com/watch?v=eCAtX9GUUjY',
 'https://www.youtube.com/watch?v=1mUo2d02RvA',
 'https://www.youtube.com/watch?v=P3hIgUgbAvs',
 'https://www.youtube.com/watch?v=o5fo2xuI4n0',
 'https://www.youtube.com/watch?v=SOsCYoWOHwg',
 'https://www.youtube.com/watch?v=FIy9NzeG2ao',
 'https://www.youtube.com/watch?v=HGQhKDtThZA',
 'https://www.youtube.com/watch?v=qBYxFz

In [242]:
fox_urls_202104 = scrape_urls(fox_channel_id, topic, max_result, start_dates[3], end_dates[3])
fox_urls_202104

['https://www.youtube.com/watch?v=8ZVfVwvvkHQ',
 'https://www.youtube.com/watch?v=1iHDPea-liE',
 'https://www.youtube.com/watch?v=QDIfFb5z7eQ',
 'https://www.youtube.com/watch?v=rpa1F5895CA',
 'https://www.youtube.com/watch?v=mx-0etLwuo0',
 'https://www.youtube.com/watch?v=dMmnoAb7ic0',
 'https://www.youtube.com/watch?v=tgPltET5oo8',
 'https://www.youtube.com/watch?v=mvi4wTwEfIw',
 'https://www.youtube.com/watch?v=VI8q55naiAQ',
 'https://www.youtube.com/watch?v=SCZG1ENZB90',
 'https://www.youtube.com/watch?v=kDvHqvFLENQ',
 'https://www.youtube.com/watch?v=atb2Qgfs8Ig',
 'https://www.youtube.com/watch?v=Tz3cd-RcIcY',
 'https://www.youtube.com/watch?v=BFHyE7arNP0',
 'https://www.youtube.com/watch?v=BC1o4__XZM4',
 'https://www.youtube.com/watch?v=RAs9ZG0ZwAo',
 'https://www.youtube.com/watch?v=2lPKt8lGmto',
 'https://www.youtube.com/watch?v=b3BgBFNzqcQ',
 'https://www.youtube.com/watch?v=uhRK_IYyxwE',
 'https://www.youtube.com/watch?v=j_cmQeEyTMQ',
 'https://www.youtube.com/watch?v=uXefE-

In [243]:
fox_urls_202105 = scrape_urls(fox_channel_id, topic, max_result, start_dates[4], end_dates[4])
fox_urls_202105

['https://www.youtube.com/watch?v=ylLf2o5mSR4',
 'https://www.youtube.com/watch?v=GaEYog4Alx0',
 'https://www.youtube.com/watch?v=1EVSBvtsfSo',
 'https://www.youtube.com/watch?v=skwc8kIS118',
 'https://www.youtube.com/watch?v=QYC9jH959a0',
 'https://www.youtube.com/watch?v=41msUMrfEYw',
 'https://www.youtube.com/watch?v=QvEjqhFb-o8',
 'https://www.youtube.com/watch?v=wI0PCKtD9wg',
 'https://www.youtube.com/watch?v=SUP8TamjYcY',
 'https://www.youtube.com/watch?v=7Vv_BIc1SPc',
 'https://www.youtube.com/watch?v=kaWiohN15PQ',
 'https://www.youtube.com/watch?v=rjzFTdu057s',
 'https://www.youtube.com/watch?v=H2DmqAg9lwc',
 'https://www.youtube.com/watch?v=Brv0DalK9hg',
 'https://www.youtube.com/watch?v=dCgUTUdFVlk',
 'https://www.youtube.com/watch?v=lKg1n0Ev7DY',
 'https://www.youtube.com/watch?v=lpHooGxc7-A',
 'https://www.youtube.com/watch?v=wE8NvFi01uI',
 'https://www.youtube.com/watch?v=uQAen9YskI0',
 'https://www.youtube.com/watch?v=OQRYLOzTVZ0',
 'https://www.youtube.com/watch?v=xXwhP2

In [244]:
fox_urls_202106 = scrape_urls(fox_channel_id, topic, max_result, start_dates[5], end_dates[5])
fox_urls_202106

['https://www.youtube.com/watch?v=jh3huU1F_EM',
 'https://www.youtube.com/watch?v=GO8xASF4ClI',
 'https://www.youtube.com/watch?v=Z89OtQT9RpI',
 'https://www.youtube.com/watch?v=E3bQ74z6RHw',
 'https://www.youtube.com/watch?v=32V-e7saq60',
 'https://www.youtube.com/watch?v=0KBJjBXkGx0',
 'https://www.youtube.com/watch?v=Dfd1li0Z1tU',
 'https://www.youtube.com/watch?v=faRC9uXv3sw',
 'https://www.youtube.com/watch?v=pDkgoAvV0B0',
 'https://www.youtube.com/watch?v=DghzRS5Ev40',
 'https://www.youtube.com/watch?v=ZiCoif63QrM',
 'https://www.youtube.com/watch?v=tas91MvcZvU',
 'https://www.youtube.com/watch?v=DDX6Rn5pA6w',
 'https://www.youtube.com/watch?v=gCwljeWLMTg',
 'https://www.youtube.com/watch?v=yxXfVV2SfDA',
 'https://www.youtube.com/watch?v=vIMQMBO9nMI',
 'https://www.youtube.com/watch?v=xEYde1qjrtY',
 'https://www.youtube.com/watch?v=10sAQ7v6CxQ',
 'https://www.youtube.com/watch?v=CQRxhLEmgW8',
 'https://www.youtube.com/watch?v=TZW8gsLBfYE',
 'https://www.youtube.com/watch?v=rRZqOo

In [245]:
fox_urls_202107 = scrape_urls(fox_channel_id, topic, max_result, start_dates[6], end_dates[6])
fox_urls_202107

['https://www.youtube.com/watch?v=4JFABUkRaO0',
 'https://www.youtube.com/watch?v=TQO54vyD8n8',
 'https://www.youtube.com/watch?v=HBeiLPl5TlM',
 'https://www.youtube.com/watch?v=yij89AyMh3A',
 'https://www.youtube.com/watch?v=FFM_kB59GE0',
 'https://www.youtube.com/watch?v=dvTof7hVDsU',
 'https://www.youtube.com/watch?v=trVD8CSKMbQ',
 'https://www.youtube.com/watch?v=iHXztL5KvAE',
 'https://www.youtube.com/watch?v=a0erYlecVkc',
 'https://www.youtube.com/watch?v=uKiak1IzE6g',
 'https://www.youtube.com/watch?v=anB6ES1eah0',
 'https://www.youtube.com/watch?v=KhMTa7FrQwQ',
 'https://www.youtube.com/watch?v=438vTU6DMP8',
 'https://www.youtube.com/watch?v=JdnqbBjDhBA',
 'https://www.youtube.com/watch?v=SVcvCPTANMI',
 'https://www.youtube.com/watch?v=8yABeVTU3oU',
 'https://www.youtube.com/watch?v=_iL4bliNBB0',
 'https://www.youtube.com/watch?v=coof2vR3nHU',
 'https://www.youtube.com/watch?v=7fQ9dOgee34',
 'https://www.youtube.com/watch?v=oyqDoSlCWfQ',
 'https://www.youtube.com/watch?v=rdaoBb

In [246]:
fox_urls_202108 = scrape_urls(fox_channel_id, topic, max_result, start_dates[7], end_dates[7])
fox_urls_202108

['https://www.youtube.com/watch?v=skSPOe4Xbf0',
 'https://www.youtube.com/watch?v=u1_zG9EEAtw',
 'https://www.youtube.com/watch?v=ZupV0Du--LM',
 'https://www.youtube.com/watch?v=mF_zJR-xvGY',
 'https://www.youtube.com/watch?v=D3HeAa793JI',
 'https://www.youtube.com/watch?v=V73BWzHAZDk',
 'https://www.youtube.com/watch?v=qUkuRTPig4s',
 'https://www.youtube.com/watch?v=nIgso3yJ4F4',
 'https://www.youtube.com/watch?v=vNf7chKd4T4',
 'https://www.youtube.com/watch?v=HoL-OwlKMP0',
 'https://www.youtube.com/watch?v=TGEwf9hAwrs',
 'https://www.youtube.com/watch?v=D1q-tvrKG5Y',
 'https://www.youtube.com/watch?v=SfIhpGC_gNc',
 'https://www.youtube.com/watch?v=CfItfZMjGTo',
 'https://www.youtube.com/watch?v=ji8oHI6A44Q',
 'https://www.youtube.com/watch?v=laLdp_LwJGc',
 'https://www.youtube.com/watch?v=i4iYv37V3Bs',
 'https://www.youtube.com/watch?v=SVZ6hyKgfIk',
 'https://www.youtube.com/watch?v=kW3jhIw1QMw',
 'https://www.youtube.com/watch?v=bNh-batUnxw',
 'https://www.youtube.com/watch?v=xIrrN9

In [247]:
fox_urls_202109 = scrape_urls(fox_channel_id, topic, max_result, start_dates[8], end_dates[8])
fox_urls_202109

['https://www.youtube.com/watch?v=jpJH88CfozU',
 'https://www.youtube.com/watch?v=Q2gH25MVTAI',
 'https://www.youtube.com/watch?v=iof3X0AxAw8',
 'https://www.youtube.com/watch?v=52N4kACEbz4',
 'https://www.youtube.com/watch?v=RSdscAMK66Y',
 'https://www.youtube.com/watch?v=pm1y8SIYabg',
 'https://www.youtube.com/watch?v=L6rW5BO-pmY',
 'https://www.youtube.com/watch?v=55ytQzdFDZg',
 'https://www.youtube.com/watch?v=6E1sli7UYkE',
 'https://www.youtube.com/watch?v=eAVuBgR6iZw',
 'https://www.youtube.com/watch?v=mzkb1F-2gKA',
 'https://www.youtube.com/watch?v=_cx5P_y8ckQ',
 'https://www.youtube.com/watch?v=J7gYrNmC1rs',
 'https://www.youtube.com/watch?v=9pjht_b9H5s',
 'https://www.youtube.com/watch?v=akOnl0zpqYo',
 'https://www.youtube.com/watch?v=hEQqrOI-a5Y',
 'https://www.youtube.com/watch?v=75sUi4-IbhQ',
 'https://www.youtube.com/watch?v=EHX23_MdJww',
 'https://www.youtube.com/watch?v=qI9kOw4K6is',
 'https://www.youtube.com/watch?v=akLj7D4tZ1k',
 'https://www.youtube.com/watch?v=TPPXT0

In [248]:
fox_urls_202110 = scrape_urls(fox_channel_id, topic, max_result, start_dates[9], end_dates[9])
fox_urls_202110

['https://www.youtube.com/watch?v=B_W7QV1JtZY',
 'https://www.youtube.com/watch?v=8Qf5l2nmWOY',
 'https://www.youtube.com/watch?v=nZgdFtUJmHA',
 'https://www.youtube.com/watch?v=deU89o33Z0c',
 'https://www.youtube.com/watch?v=PSflv_Fkosc',
 'https://www.youtube.com/watch?v=imDt_D8yoW0',
 'https://www.youtube.com/watch?v=A8Se8c5K0BQ',
 'https://www.youtube.com/watch?v=hh2Uc--DiOg',
 'https://www.youtube.com/watch?v=57gMBrXaGmw',
 'https://www.youtube.com/watch?v=SQtbx-aJoaY',
 'https://www.youtube.com/watch?v=JPU7lmS438k',
 'https://www.youtube.com/watch?v=IkjvN5TmJTA',
 'https://www.youtube.com/watch?v=C-InGKj450U',
 'https://www.youtube.com/watch?v=nZZY7rzN1aA',
 'https://www.youtube.com/watch?v=2thwVRZm1S8',
 'https://www.youtube.com/watch?v=QpUN5TQwjpw',
 'https://www.youtube.com/watch?v=fN6PiO-dcps',
 'https://www.youtube.com/watch?v=Vmixv8Zp9ps',
 'https://www.youtube.com/watch?v=C-SsEIaHcLE',
 'https://www.youtube.com/watch?v=r4Jn_XAMP_I',
 'https://www.youtube.com/watch?v=i_RoGZ

In [249]:
fox_urls_202111 = scrape_urls(fox_channel_id, topic, max_result, start_dates[10], end_dates[10])
fox_urls_202111

['https://www.youtube.com/watch?v=fuYItDzKh9w',
 'https://www.youtube.com/watch?v=DPr0kRTlQEE',
 'https://www.youtube.com/watch?v=3hH-QaTV8bM',
 'https://www.youtube.com/watch?v=6mqd1telQYM',
 'https://www.youtube.com/watch?v=LTsBZAM73r4',
 'https://www.youtube.com/watch?v=-uGcWuVbfcM',
 'https://www.youtube.com/watch?v=AXHYgn3g-wQ',
 'https://www.youtube.com/watch?v=B2L42s0WrDo',
 'https://www.youtube.com/watch?v=FaYMIwdERRw',
 'https://www.youtube.com/watch?v=SGTeBC0fJyA',
 'https://www.youtube.com/watch?v=V4dfC6suqos',
 'https://www.youtube.com/watch?v=3_x6vTJr3vA',
 'https://www.youtube.com/watch?v=lmocuFs48gM',
 'https://www.youtube.com/watch?v=vJ1_SwGOAGw',
 'https://www.youtube.com/watch?v=tFVHaasYIx4',
 'https://www.youtube.com/watch?v=Yx9E6BUSPs4',
 'https://www.youtube.com/watch?v=7oWaUOHNdds',
 'https://www.youtube.com/watch?v=mTkcXJRYuq0',
 'https://www.youtube.com/watch?v=bA9Bot0Mnmk',
 'https://www.youtube.com/watch?v=jzn045EtcQc',
 'https://www.youtube.com/watch?v=385_5O

In [251]:
fox_urls_202112 = scrape_urls(fox_channel_id, topic, max_result, start_dates[11], '2021-12-31T23:59:59Z')
fox_urls_202112

['https://www.youtube.com/watch?v=_yeXXQacPZc',
 'https://www.youtube.com/watch?v=1aRgvx7v1aI',
 'https://www.youtube.com/watch?v=XurbjBtejrg',
 'https://www.youtube.com/watch?v=EySxIRZdMy8',
 'https://www.youtube.com/watch?v=RV9_GTOhgc4',
 'https://www.youtube.com/watch?v=GUsKypt4vs0',
 'https://www.youtube.com/watch?v=2JGYaGd3CR8',
 'https://www.youtube.com/watch?v=zWOz9lbTN54',
 'https://www.youtube.com/watch?v=pcN7pLj7Eys',
 'https://www.youtube.com/watch?v=wj2EYN3-3uc',
 'https://www.youtube.com/watch?v=nv_OAqDx7pc',
 'https://www.youtube.com/watch?v=M0ja1CkMFa4',
 'https://www.youtube.com/watch?v=-7Eq7CeIOYg',
 'https://www.youtube.com/watch?v=AFn6wNjhL18',
 'https://www.youtube.com/watch?v=ixMYi-jOplw',
 'https://www.youtube.com/watch?v=SrHeC6d2Ilk',
 'https://www.youtube.com/watch?v=ICBbHV2ZV5Y',
 'https://www.youtube.com/watch?v=UGggZmA3Nlk',
 'https://www.youtube.com/watch?v=VTdA6TgHa2Y',
 'https://www.youtube.com/watch?v=QEC2gB77sHw',
 'https://www.youtube.com/watch?v=gDOKra

In [252]:
fox_2021_lst = [fox_urls_202101, fox_urls_202102,
                fox_urls_202103, fox_urls_202104,
                fox_urls_202105, fox_urls_202106,
                fox_urls_202107, fox_urls_202108,
                fox_urls_202109, fox_urls_202110,
                fox_urls_202111, fox_urls_202112]

with open("/Users/itsyuzhou/Autumn2023/MA_thesis/fox_urls_2021.csv", mode='w', newline='') as file:
    writer = csv.writer(file)

    for urls_monthly in fox_2021_lst:
        for url in urls_monthly:
            writer.writerow([url])
        writer.writerow([])

In [253]:
total_video = 0
month = 0
monthly_videos_counts = []
for url_lst in fox_2021_lst:
    month += 1
    monthly_videos_counts.append((month, len(url_lst)))

print(monthly_videos_counts)

for (month, monthly_count) in monthly_videos_counts:
    total_video += monthly_count
print("Fox 2021 total video counts=", total_video)

[(1, 30), (2, 30), (3, 30), (4, 30), (5, 30), (6, 30), (7, 30), (8, 30), (9, 30), (10, 30), (11, 30), (12, 30)]
Fox 2021 total video counts= 360


### 3.2 ABC 2021

In [254]:
abc_urls_202101 = scrape_urls(abc_channel_id, topic, max_result, start_dates[0], end_dates[0])
abc_urls_202101

['https://www.youtube.com/watch?v=HLr7F45BFxg',
 'https://www.youtube.com/watch?v=U3vSWmLALZo',
 'https://www.youtube.com/watch?v=u4aQNxIdWEw',
 'https://www.youtube.com/watch?v=ROjKi7tXNws',
 'https://www.youtube.com/watch?v=X92Mg1APbl8',
 'https://www.youtube.com/watch?v=09E9M7KGjKw',
 'https://www.youtube.com/watch?v=S7u2oORy0L0',
 'https://www.youtube.com/watch?v=-bnlSRwznXI',
 'https://www.youtube.com/watch?v=pJnpfPgkiQc',
 'https://www.youtube.com/watch?v=RdvT81MUUUY',
 'https://www.youtube.com/watch?v=mQrjjLqHCE0',
 'https://www.youtube.com/watch?v=CvUKDbE15Hc',
 'https://www.youtube.com/watch?v=EmgE53hXEEo',
 'https://www.youtube.com/watch?v=Caz3KDgFjdI',
 'https://www.youtube.com/watch?v=7BvOn3OaKD8',
 'https://www.youtube.com/watch?v=6MD5SU1J97s',
 'https://www.youtube.com/watch?v=1YqrZGBzr28',
 'https://www.youtube.com/watch?v=GvwRdJ4Byao',
 'https://www.youtube.com/watch?v=2s5DMIGKrjQ',
 'https://www.youtube.com/watch?v=euDsj0ZcoVE',
 'https://www.youtube.com/watch?v=zMjZ2E

In [255]:
abc_urls_202102 = scrape_urls(abc_channel_id, topic, max_result, start_dates[1], end_dates[1])
abc_urls_202103 = scrape_urls(abc_channel_id, topic, max_result, start_dates[2], end_dates[2])
abc_urls_202104 = scrape_urls(abc_channel_id, topic, max_result, start_dates[3], end_dates[3])

In [257]:
abc_urls_202105 = scrape_urls(abc_channel_id, topic, max_result, start_dates[4], end_dates[4])
abc_urls_202106 = scrape_urls(abc_channel_id, topic, max_result, start_dates[5], end_dates[5])
abc_urls_202107 = scrape_urls(abc_channel_id, topic, max_result, start_dates[6], end_dates[6])

In [259]:
abc_urls_202108 = scrape_urls(abc_channel_id, topic, max_result, start_dates[7], end_dates[7])
abc_urls_202109 = scrape_urls(abc_channel_id, topic, max_result, start_dates[8], end_dates[8])
abc_urls_202110 = scrape_urls(abc_channel_id, topic, max_result, start_dates[9], end_dates[9])

In [261]:
abc_urls_202111 = scrape_urls(abc_channel_id, topic, max_result, start_dates[10], end_dates[10])
abc_urls_202112 = scrape_urls(abc_channel_id, topic, max_result, start_dates[11], '2021-12-31T23:59:59Z')

In [263]:
abc_2021_lst = [abc_urls_202101, abc_urls_202102,
                abc_urls_202103, abc_urls_202104,
                abc_urls_202105, abc_urls_202106,
                abc_urls_202107, abc_urls_202108,
                abc_urls_202109, abc_urls_202110,
                abc_urls_202111, abc_urls_202112]

with open("/Users/itsyuzhou/Autumn2023/MA_thesis/abc_urls_2021.csv", mode='w', newline='') as file:
    writer = csv.writer(file)

    for urls_monthly in abc_2021_lst:
        for url in urls_monthly:
            writer.writerow([url])
        writer.writerow([])

In [264]:
total_video, month, monthly_videos_counts = 0, 0, []
for url_lst in abc_2021_lst:
    month += 1
    monthly_videos_counts.append((month, len(url_lst)))
print(monthly_videos_counts)
for (month, monthly_count) in monthly_videos_counts:
    total_video += monthly_count
print("ABC 2021 total video counts=", total_video)

[(1, 30), (2, 30), (3, 30), (4, 30), (5, 30), (6, 30), (7, 30), (8, 30), (9, 30), (10, 30), (11, 30), (12, 30)]
ABC 2021 total video counts= 360


### 3.3 VOX 2021

In [265]:
vox_urls_202101 = scrape_urls(vox_channel_id, topic, max_result, start_dates[0], end_dates[0])
vox_urls_202102 = scrape_urls(vox_channel_id, topic, max_result, start_dates[1], end_dates[1])
vox_urls_202103 = scrape_urls(vox_channel_id, topic, max_result, start_dates[2], end_dates[2])

In [267]:
vox_urls_202104 = scrape_urls(vox_channel_id, topic, max_result, start_dates[3], end_dates[3])
vox_urls_202105 = scrape_urls(vox_channel_id, topic, max_result, start_dates[4], end_dates[4])
vox_urls_202106 = scrape_urls(vox_channel_id, topic, max_result, start_dates[5], end_dates[5])

In [269]:
vox_urls_202107 = scrape_urls(vox_channel_id, topic, max_result, start_dates[6], end_dates[6])
vox_urls_202108 = scrape_urls(vox_channel_id, topic, max_result, start_dates[7], end_dates[7])
vox_urls_202109 = scrape_urls(vox_channel_id, topic, max_result, start_dates[8], end_dates[8])

In [272]:
vox_urls_202110 = scrape_urls(vox_channel_id, topic, max_result, start_dates[9], end_dates[9])
vox_urls_202111 = scrape_urls(vox_channel_id, topic, max_result, start_dates[10], end_dates[10])
vox_urls_202112 = scrape_urls(vox_channel_id, topic, max_result, start_dates[11], '2021-12-31T23:59:59Z')

In [274]:
vox_2021_lst = [vox_urls_202101, vox_urls_202102,
                vox_urls_202103, vox_urls_202104,
                vox_urls_202105, vox_urls_202106,
                vox_urls_202107, vox_urls_202108,
                vox_urls_202109, vox_urls_202110,
                vox_urls_202111, vox_urls_202112]

with open("/Users/itsyuzhou/Autumn2023/MA_thesis/vox_urls_2021.csv", mode='w', newline='') as file:
    writer = csv.writer(file)

    for urls_monthly in vox_2021_lst:
        for url in urls_monthly:
            writer.writerow([url])
        writer.writerow([])

In [275]:
total_video, month, monthly_videos_counts = 0, 0, []
for url_lst in vox_2021_lst:
    month += 1
    monthly_videos_counts.append((month, len(url_lst)))
print(monthly_videos_counts)
for (month, monthly_count) in monthly_videos_counts:
    total_video += monthly_count
print("Vox 2021 total video counts=", total_video)

[(1, 3), (2, 5), (3, 7), (4, 9), (5, 4), (6, 5), (7, 9), (8, 7), (9, 5), (10, 1), (11, 4), (12, 6)]
Vox 2021 total video counts= 65


### 3.4 Steve Turley 2021

In [276]:
st_urls_202101 = scrape_urls(SteveTurley_channel_id, topic, max_result, start_dates[0], end_dates[0])
st_urls_202102 = scrape_urls(SteveTurley_channel_id, topic, max_result, start_dates[1], end_dates[1])
st_urls_202103 = scrape_urls(SteveTurley_channel_id, topic, max_result, start_dates[2], end_dates[2])
st_urls_202104 = scrape_urls(SteveTurley_channel_id, topic, max_result, start_dates[3], end_dates[3])
st_urls_202105 = scrape_urls(SteveTurley_channel_id, topic, max_result, start_dates[4], end_dates[4])
st_urls_202106 = scrape_urls(SteveTurley_channel_id, topic, max_result, start_dates[5], end_dates[5])

In [279]:
st_urls_202107 = scrape_urls(SteveTurley_channel_id, topic, max_result, start_dates[6], end_dates[6])
st_urls_202108 = scrape_urls(SteveTurley_channel_id, topic, max_result, start_dates[7], end_dates[7])
st_urls_202109 = scrape_urls(SteveTurley_channel_id, topic, max_result, start_dates[8], end_dates[8])
st_urls_202110 = scrape_urls(SteveTurley_channel_id, topic, max_result, start_dates[9], end_dates[9])
st_urls_202111 = scrape_urls(SteveTurley_channel_id, topic, max_result, start_dates[10], end_dates[10])
st_urls_202112 = scrape_urls(SteveTurley_channel_id, topic, max_result, start_dates[11], '2021-12-31T23:59:59Z')

In [281]:
st_2021_lst = [st_urls_202101, st_urls_202102,
            st_urls_202103, st_urls_202104,
            st_urls_202105, st_urls_202106,
            st_urls_202107, st_urls_202108,
            st_urls_202109, st_urls_202110,
            st_urls_202111, st_urls_202112]

with open("/Users/itsyuzhou/Autumn2023/MA_thesis/st_urls_2021.csv", mode='w', newline='') as file:
    writer = csv.writer(file)

    for urls_monthly in st_2021_lst:
        for url in urls_monthly:
            writer.writerow([url])
        writer.writerow([])

In [283]:
total_video, month, monthly_videos_counts = 0, 0, []
for url_lst in st_2021_lst:
    month += 1
    monthly_videos_counts.append((month, len(url_lst)))
print(monthly_videos_counts)
for (month, monthly_count) in monthly_videos_counts:
    total_video += monthly_count
print("Steve Turley 2021 total video counts=", total_video)

[(1, 30), (2, 30), (3, 30), (4, 29), (5, 30), (6, 25), (7, 20), (8, 29), (9, 24), (10, 18), (11, 18), (12, 30)]
Steve Turley 2021 total video counts= 313


### 3.5 Kim Iversen 2021

In [284]:
ki_urls_202101 = scrape_urls(KimIversen_channel_id, topic, max_result, start_dates[0], end_dates[0])
ki_urls_202102 = scrape_urls(KimIversen_channel_id, topic, max_result, start_dates[1], end_dates[1])
ki_urls_202103 = scrape_urls(KimIversen_channel_id, topic, max_result, start_dates[2], end_dates[2])
ki_urls_202104 = scrape_urls(KimIversen_channel_id, topic, max_result, start_dates[3], end_dates[3])
ki_urls_202105 = scrape_urls(KimIversen_channel_id, topic, max_result, start_dates[4], end_dates[4])
ki_urls_202106 = scrape_urls(KimIversen_channel_id, topic, max_result, start_dates[5], end_dates[5])

In [286]:
ki_urls_202107 = scrape_urls(KimIversen_channel_id, topic, max_result, start_dates[6], end_dates[6])
ki_urls_202108 = scrape_urls(KimIversen_channel_id, topic, max_result, start_dates[7], end_dates[7])
ki_urls_202109 = scrape_urls(KimIversen_channel_id, topic, max_result, start_dates[8], end_dates[8])
ki_urls_202110 = scrape_urls(KimIversen_channel_id, topic, max_result, start_dates[9], end_dates[9])
ki_urls_202111 = scrape_urls(KimIversen_channel_id, topic, max_result, start_dates[10], end_dates[10])
ki_urls_202112 = scrape_urls(KimIversen_channel_id, topic, max_result, start_dates[11], '2021-12-31T23:59:59Z')

In [292]:
ki_2021_lst = [ki_urls_202101, ki_urls_202102,
            ki_urls_202103, ki_urls_202104,
            ki_urls_202105, ki_urls_202106,
            ki_urls_202107, ki_urls_202108,
            ki_urls_202109, ki_urls_202110,
            ki_urls_202111, ki_urls_202112]

with open("/Users/itsyuzhou/Autumn2023/MA_thesis/ki_urls_2021.csv", mode='w', newline='') as file:
    writer = csv.writer(file)

    for urls_monthly in ki_2021_lst:
        for url in urls_monthly:
            writer.writerow([url])
        writer.writerow([])

In [293]:
total_video, month, monthly_videos_counts = 0, 0, []
for url_lst in ki_2021_lst:
    month += 1
    monthly_videos_counts.append((month, len(url_lst)))
print(monthly_videos_counts)
for (month, monthly_count) in monthly_videos_counts:
    total_video += monthly_count
print("Kim Iversen 2021 total video counts=", total_video)

[(1, 16), (2, 26), (3, 21), (4, 25), (5, 9), (6, 14), (7, 7), (8, 7), (9, 2), (10, 0), (11, 0), (12, 0)]
Kim Iversen 2021 total video counts= 127


### 3.6 Robert Reich 2021

In [294]:
rr_urls_202101 = scrape_urls(RobertReich_channel_id, topic, max_result, start_dates[0], end_dates[0])
rr_urls_202102 = scrape_urls(RobertReich_channel_id, topic, max_result, start_dates[1], end_dates[1])
rr_urls_202103 = scrape_urls(RobertReich_channel_id, topic, max_result, start_dates[2], end_dates[2])
rr_urls_202104 = scrape_urls(RobertReich_channel_id, topic, max_result, start_dates[3], end_dates[3])
rr_urls_202105 = scrape_urls(RobertReich_channel_id, topic, max_result, start_dates[4], end_dates[4])
rr_urls_202106 = scrape_urls(RobertReich_channel_id, topic, max_result, start_dates[5], end_dates[5])

In [299]:
rr_urls_202107 = scrape_urls(RobertReich_channel_id, topic, max_result, start_dates[6], end_dates[6])
rr_urls_202108 = scrape_urls(RobertReich_channel_id, topic, max_result, start_dates[7], end_dates[7])
rr_urls_202109 = scrape_urls(RobertReich_channel_id, topic, max_result, start_dates[8], end_dates[8])
rr_urls_202110 = scrape_urls(RobertReich_channel_id, topic, max_result, start_dates[9], end_dates[9])
rr_urls_202111 = scrape_urls(RobertReich_channel_id, topic, max_result, start_dates[10], end_dates[10])
rr_urls_202112 = scrape_urls(RobertReich_channel_id, topic, max_result, start_dates[11], '2021-12-31T23:59:59Z')

In [306]:
rr_2021_lst = [rr_urls_202101, rr_urls_202102,
            rr_urls_202103, rr_urls_202104,
            rr_urls_202105, rr_urls_202106,
            rr_urls_202107, rr_urls_202108,
            rr_urls_202109, rr_urls_202110,
            rr_urls_202111, rr_urls_202112]

with open("/Users/itsyuzhou/Autumn2023/MA_thesis/rr_urls_2021.csv", mode='w', newline='') as file:
    writer = csv.writer(file)

    for urls_monthly in rr_2021_lst:
        for url in urls_monthly:
            writer.writerow([url])
        writer.writerow([])

In [307]:
total_video, month, monthly_videos_counts = 0, 0, []
for url_lst in rr_2021_lst:
    month += 1
    monthly_videos_counts.append((month, len(url_lst)))
print(monthly_videos_counts)
for (month, monthly_count) in monthly_videos_counts:
    total_video += monthly_count
print("Robert Reich 2021 total video counts=", total_video)

[(1, 2), (2, 3), (3, 5), (4, 0), (5, 2), (6, 7), (7, 7), (8, 1), (9, 2), (10, 3), (11, 2), (12, 3)]
Robert Reich 2021 total video counts= 37


### 3.7 MSNBC 2020

In [8]:
start_dates, end_dates = generate_start_end_time(2020)
topic = 'covid'
max_result = 30

In [9]:
MSNBC_urls_202001 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[0], end_dates[0])
MSNBC_urls_202002 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[1], end_dates[1])
MSNBC_urls_202003 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[2], end_dates[2])
MSNBC_urls_202004 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[3], end_dates[3])
MSNBC_urls_202005 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[4], end_dates[4])
MSNBC_urls_202006 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[5], end_dates[5])

In [10]:
MSNBC_urls_202007 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[6], end_dates[6])
MSNBC_urls_202008 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[7], end_dates[7])
MSNBC_urls_202009 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[8], end_dates[8])
MSNBC_urls_202010 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[9], end_dates[9])
MSNBC_urls_202011 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[10], end_dates[10])
MSNBC_urls_202012 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[11], '2020-12-31T23:59:59Z')

In [11]:
MSNBC_2020_lst = [MSNBC_urls_202001, MSNBC_urls_202002,
            MSNBC_urls_202003, MSNBC_urls_202004,
            MSNBC_urls_202005, MSNBC_urls_202006,
            MSNBC_urls_202007, MSNBC_urls_202008,
            MSNBC_urls_202009, MSNBC_urls_202010,
            MSNBC_urls_202011, MSNBC_urls_202012]

with open("/Users/itsyuzhou/Autumn2023/MA_thesis/msnbc_urls_2020.csv", mode='w', newline='') as file:
    writer = csv.writer(file)

    for urls_monthly in MSNBC_2020_lst:
        for url in urls_monthly:
            writer.writerow([url])
        writer.writerow([])

### 3.8 MSNBC 2021

In [12]:
start_dates, end_dates = generate_start_end_time(2021)
topic = 'covid'
max_result = 30

In [13]:
MSNBC_urls_202101 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[0], end_dates[0])
MSNBC_urls_202102 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[1], end_dates[1])
MSNBC_urls_202103 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[2], end_dates[2])
MSNBC_urls_202104 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[3], end_dates[3])
MSNBC_urls_202105 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[4], end_dates[4])
MSNBC_urls_202106 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[5], end_dates[5])

In [14]:
MSNBC_urls_202107 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[6], end_dates[6])
MSNBC_urls_202108 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[7], end_dates[7])
MSNBC_urls_202109 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[8], end_dates[8])
MSNBC_urls_202110 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[9], end_dates[9])
MSNBC_urls_202111 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[10], end_dates[10])
MSNBC_urls_202112 = scrape_urls(msnbc_channel_id, topic, max_result, start_dates[11], '2021-12-31T23:59:59Z')

In [15]:
MSNBC_2021_lst = [MSNBC_urls_202101, MSNBC_urls_202102,
            MSNBC_urls_202103, MSNBC_urls_202104,
            MSNBC_urls_202105, MSNBC_urls_202106,
            MSNBC_urls_202107, MSNBC_urls_202108,
            MSNBC_urls_202109, MSNBC_urls_202110,
            MSNBC_urls_202111, MSNBC_urls_202112]

with open("/Users/itsyuzhou/Autumn2023/MA_thesis/msnbc_urls_2021.csv", mode='w', newline='') as file:
    writer = csv.writer(file)

    for urls_monthly in MSNBC_2021_lst:
        for url in urls_monthly:
            writer.writerow([url])
        writer.writerow([])

## 4. Random Sampling to Check for Video Relevancy

In [5]:
fox_2020 = pd.read_csv("/Users/itsyuzhou/Autumn2023/MA_thesis/fox_urls.csv")
fox_2021 = pd.read_csv("/Users/itsyuzhou/Autumn2023/MA_thesis/fox_urls_2021.csv")
abc_2020 = pd.read_csv("/Users/itsyuzhou/Autumn2023/MA_thesis/abc_url.csv")
abc_2021 = pd.read_csv("/Users/itsyuzhou/Autumn2023/MA_thesis/abc_urls_2021.csv")
vox_2020 = pd.read_csv("/Users/itsyuzhou/Autumn2023/MA_thesis/vox_url.csv")
vox_2021 = pd.read_csv("/Users/itsyuzhou/Autumn2023/MA_thesis/vox_urls_2021.csv")
st_2020 = pd.read_csv("/Users/itsyuzhou/Autumn2023/MA_thesis/steveturley_urls.csv")
st_2021 = pd.read_csv("/Users/itsyuzhou/Autumn2023/MA_thesis/st_urls_2021.csv")
ki_2020 = pd.read_csv("/Users/itsyuzhou/Autumn2023/MA_thesis/kimiversen_url.csv")
ki_2021 = pd.read_csv("/Users/itsyuzhou/Autumn2023/MA_thesis/ki_urls_2021.csv")
rr_2020 = pd.read_csv("/Users/itsyuzhou/Autumn2023/MA_thesis/robertreich_url.csv")
rr_2021 = pd.read_csv("/Users/itsyuzhou/Autumn2023/MA_thesis/rr_urls_2021.csv")

In [8]:
fox_len2020 = len(fox_2020)
fox_len2021 = len(fox_2021)
abc_len2020 = len(abc_2020)
abc_len2021 = len(abc_2021)
vox_len2020 = len(vox_2020)
vox_len2021 = len(vox_2021)
st_len2020 = len(st_2020)
st_len2021 = len(st_2021)
ki_len2020 = len(ki_2020)
ki_len2021 = len(ki_2021)
rr_len2020 = len(rr_2020)
rr_len2021 = len(rr_2021)

In [10]:
# Generate random numbers
fox_random_numbers2020 = [random.randint(0, fox_len2020) for _ in range(5)]
fox_random_numbers2021 = [random.randint(0, fox_len2021) for _ in range(5)]
abc_random_numbers2020 = [random.randint(0, abc_len2020) for _ in range(5)]
abc_random_numbers2021 = [random.randint(0, abc_len2021) for _ in range(5)]
vox_random_numbers2020 = [random.randint(0, vox_len2020) for _ in range(5)]
vox_random_numbers2021 = [random.randint(0, vox_len2021) for _ in range(5)]
st_random_numbers2020 = [random.randint(0, st_len2020) for _ in range(5)]
st_random_numbers2021 = [random.randint(0, st_len2021) for _ in range(5)]
ki_random_numbers2020 = [random.randint(0, ki_len2020) for _ in range(5)]
ki_random_numbers2021 = [random.randint(0, ki_len2021) for _ in range(5)]
rr_random_numbers2020 = [random.randint(0, rr_len2020) for _ in range(5)]
rr_random_numbers2021 = [random.randint(0, rr_len2021) for _ in range(5)]

In [12]:
print('Fox random videos: ', fox_random_numbers2020, fox_random_numbers2021)
print('ABC random videos: ', abc_random_numbers2020, abc_random_numbers2021)
print('VOX random videos: ', vox_random_numbers2020, vox_random_numbers2021)
print('Steve Turley random videos: ', st_random_numbers2020, st_random_numbers2021)
print('Kim Iversen random videos: ', ki_random_numbers2020, ki_random_numbers2021)
print('Robert Reich random videos: ', rr_random_numbers2020, rr_random_numbers2021)

Fox random videos:  [61, 63, 15, 66, 33] [328, 234, 249, 104, 39]
ABC random videos:  [258, 228, 149, 222, 179] [272, 280, 266, 315, 61]
VOX random videos:  [36, 43, 40, 9, 6] [17, 29, 30, 43, 21]
Steve Turley random videos:  [111, 11, 30, 146, 161] [229, 61, 312, 264, 52]
Kim Iversen random videos:  [19, 21, 33, 11, 36] [41, 11, 26, 120, 27]
Robert Reich random videos:  [44, 0, 11, 69, 10] [8, 18, 6, 36, 15]


In [16]:
msnbc_2020 = pd.read_csv("/Users/itsyuzhou/Autumn2023/MA_thesis/msnbc_urls_2020.csv")
msnbc_2021 = pd.read_csv("/Users/itsyuzhou/Autumn2023/MA_thesis/msnbc_urls_2021.csv")

msnbc_len2020 = len(msnbc_2020)
msnbc_len2021 = len(msnbc_2021)

msnbc_random_numbers2020 = [random.randint(0, msnbc_len2020) for _ in range(5)]
msnbc_random_numbers2021 = [random.randint(0, msnbc_len2021) for _ in range(5)]

print('MSNBC random videos: ', msnbc_random_numbers2020, msnbc_random_numbers2021)

MSNBC random videos:  [190, 198, 7, 100, 171] [279, 271, 305, 169, 91]


### Track the relevancy and comments of randomly selected videos for each news chanel per year

If the chosen random number corresponds to an empty line, use the next line

### 1. Fox News
#### 2020
- 61: (relevant and 26,801 comments) Coronavirus whistleblower speaks out about possible COVID origin on 'Tucker'
- 63: (relevant and 1,000 comments) Steve Hilton on a big 2020 election issue: Coronavirus
- 15: (relevant and 528 comments) Medical experts provide answers to your questions on 'Fox News @ Night' (combat covid-19)
- 66: (relevant and 16,858 comments) Trump joins 'Tucker' for first on-camera interview since COVID-19 diagnosis
- 33: (relevant and 4,564 comments) Dr. Deborah Birx on the timeline for a COVID-19 vaccine, efforts to reopen America

#### 2021
- 328: (not very relevant and 12,874 comments) Biden blames Trump voters for Virginia losses, Aaron Rodgers being criticized for claiming he is immunized against COVID-19
- 234: (relevant and 1,021 comments) Border community declares state of emergency over COVID-positive migrants
- 249: (relevant and 5,223 comments) Bill Maher says liberal media COVID push 'scaring the s--- out of people'
- 104: (relevant and 287 comments) Cuccinelli: Harris' inability to visit border due to COVID a 'bad excuse'
- 39: (relevant and 673 comments) Florida governor: COVID relief bill 'calculated’ to benefit failing blue states

Unusable Proportion = 1/10 = 10%

### 2. ABC News

#### 2020
- 258: (relevant and 16,858 comments) U.S. COVID-19 death toll nears 200,000, CDC revises guidance | WNT
- 228: (relevant and 324 comments) COVID-19 crisis grows dire along US-Mexico border l GMA
- 149: (relevant and 91 comments) COVID-19 and the future of work
- 222: (less relevant and 39 comments) Used cars in high demand amid COVID-19
- 179: (relevant and 111 comments) Latest updates on COVID-19: July 6, 2020

#### 2021
- 272: (relevant and 270 comments) Pfizer’s COVID-19 booster could come by end of week l WNT
- 280: (relevant and 100 comments) COVID-19 and mental health
- 266: (relevant and 1,994 comments) Nearly every COVID-19 patient hospitalized in Boise, Idaho, is unvaccinated
- 315: (relevant and 6,065 comments) Surgeon general on combating COVID-19 vaccine misinformation
- 61: (relevant and 642 comments) Coronavirus cases drop sharply

Unusable Proportion = 1/10 = 10%


In [13]:
vox_random_numbers_2021 = [random.randint(0, vox_len2021) for _ in range(5)]
vox_random_numbers_2021

[5, 58, 21, 15, 8]

### 3. Vox News

#### 2020
- 36: (Irrelevant) Why locusts are descending on East Africa
- 43: (Irrelevant) Facebook showed this ad to 95% women. Is that a problem?
- 41: (Relevant and 2,639 comments) How humans are making pandemics more likely
- 9: (Relevant and 8,787 comments) Why fighting the coronavirus depends on you
- 6: (Relevant and 50,373 comments) How wildlife trade is linked to coronavirus

#### 2021
- 5: (Relevant and 4,397 comments) mRNA vaccines, explained
- 58: (Irrelevant) Introducing Vox’s new HBO show, Level Playing Field
- 21: (Irrelevant) Earworm is back! Here’s a preview
- 15: (Less relevant) Are We Automating Racism?
- 8: (Irrelevant) How Alexei Navalny became Putin's greatest threat

Unusable Proportion = 5/10 = 50%


### 4. Dr. Steve Turley

#### 2020
- 111: (Irrelevant) The Woke NBA CANCELS ITSELF as Their Ratings Absolutely PLUMMET!!!
- 11: (Relevant and 593 comments) Joe Biden Accused of SEXUAL ASSAULT as Coronavirus KILLS His Campaign!!!
- 30: (Irrelevant) SHOCK POLL! 15 Percent of Bernie Supporters Will Vote for Trump Over Biden!!!
- 146: (Irrelevant) CNN Analyst HUMILIATED! SUSPENDED after EXPOSING Himself on ZOOM Call!!!
- 161: (Irrelevant) Here are the 3 SCENARIOS That Can Play Out in the Next FEW WEEKS!!!

#### 2021
- 229: (Irrelevant) POLL! Trump CRUSHES Biden as Dems REGRET Their 2020 VOTE!!!
- 61: (Relevant and 1,194 comments) CNN’s Chris Cuomo COLLAPSING! BOMBSHELL Scandal Reveals Special Access to Covid Test!!!
- 312: (Irrelevant) Liberal MEDIA MELTS DOWN as Manchin KILLS Build Back Better!!!
- 264: (Irrelevant) Biden’s Polls IMPLODE as Majority Believe He CHEATED!!!
- 52: (Irrelevant) Trump’s Week of WINNING and the Path Forward for 2024!!!

Unusable Proportion = 8/10 = 80%

### Kim Iversen

#### 2020
- 19: (Irrelevant) OUSTING Debbie Wasserman Schultz! How Jen Perelman Is Going To Do It.
- 21: (Less relevant and 910 comments) The Fed and The Big Bank Wealth Heist. Why We Need Public Banking- Ellen Brown
- 33: (Less relevant on covid but relevant to anti-China, 734 comments) Trump's REAL Foreign Policy Target
- 11: (Relevant and 1,403 comments) Super-Rich Are Getting Richer During The Pandemic
- 36: (Irrelevant) Hillary Clinton Ensures Kamala Harris as VP (and then on to President)

#### 2021
Note: Some chanels (including Iversen's) labeled "medical misinformation" because they're against lockdown and censored
- 41: (Relevant and 3,081 comments) VIDEO REMOVED: Russia, China and Iran Claim Covid Came From US Lab
- 11: (Irrelevant) Joe Biden Takes More DARK MONEY Than Any Other Politician EVER
- 26: (Irrelevant) Iraq Rocket Attacks That Killed American Is Blamed On Iran - The TRUTH
- 120: (Irrelevant) Jeff Bezos THANKS Employees and Customers For His SUPER FUN Space Flight
- 27: (Relevant and 802 comments) Lockdown California Vs. No Lockdown Florida: A Look At The Numbers

Unusable Proportion = 5/10 = 50%

### Robert Reich

#### 2020
- 44: (Relevant and 993 comments) Jared Kushner & Co. Just Got a $160 Billion Tax Windfall
- 0: (Irrelevant) Should Facebook and Twitter Stop Trump's Lies?
- 11: (Relevant and 1,125 comments) How to Prepare for the Trump Recession
- 69: (Relevant and 380 comments) Betsy DeVos’ Deadly Plan to Open Schools
- 10: (Relevant and 1,244 comments) The $500 Billion Bailout, Privilege, and Accountability | The Common Good with Robert Reich

#### 2021
- 8: (Relevant and 796 comments) We Can Afford COVID Relief #shorts
- 18: (Relevant and 433 comments) 7 Lessons We Need to Learn from Covid-19
- 6: (Irrelevant) Trump Senate Trial: No Healing Without Accountability #shorts
- 36: (Irrelevant) What Happened to the Haitians at the Border?
- 15: (Irrelevant) Why Democrats are Running Out of Time

Unusable Proportion = 4/10 = 40%

### MSNBC

#### 2020
- 190: (Relevant and 197 Comments) Public Health Expert: Texas May have A New York-Level COVID-19 Crisis | The 11th Hour
- 198: (Relevant and 297 Comments) COVID-19 Is Affecting Kids' Brains Leaving Troubling Side Effects | The 11th Hour
- 7: (Relevant and 802 Comments) Man In His 20s Tests Positive For COVID-19 In Boston | MSNBC
- 100: (Relevant and 219 Comments) Laurie Garrett On COVID-19 Timeline: ‘Three Years Is My Best Case Scenario’ | The Last Word
- 171: (Relevant and 78 Comments) Masks Are Better Than Any Drug So Far Against COVID-19 | The 11th Hour | MSNBC

#### 2021
- 279: (Relevant and 211 Comments) The Bye Line: Reflecting On The Lives Lost To Covid-19
- 271: (Relevant and 66 Comments) Detroit Implements Ambitious Public School Covid Testing Program
- 305: (Relevant and 544 Comments) Powell Was Being Treated For Multiple Myeloma, Fully Vaccinated For Covid Before Death
- 169: (Relevant and 2,087 Comments) Dr. Anthony Fauci On Covid Origins, New Variant
- 91: (Relevant and 2,505 Comments) Biden Signs $1.9 Trillion Covid Relief Bill


Unusable Proportion = 0%

## 5. Randomly Choose Videos to Scrape Comments From

In [12]:
def read_csv_select_links(file_path):
    months_data = []
    current_month_data = []

    with open(file_path, 'r') as csvfile:
        reader = csv.reader(csvfile)
        
        for row in reader:
            if not row:
                if current_month_data:
                    months_data.append(current_month_data)
                    current_month_data = []
            else:
                current_month_data.append(row)

    # Select one random line from each month
    selected_lines = [random.choice(month) for month in months_data]

    return selected_lines

In [14]:
file_path = '/Users/itsyuzhou/Autumn2023/MA_thesis_repo/video_urls/fox_urls.csv'
fox_2020 = read_csv_select_links(file_path)

for line in fox_2020:
    print(line)

['https://www.youtube.com/watch?v=EbyPW8lJX2E']
['https://www.youtube.com/watch?v=jCcR3WVjhcU']
['https://www.youtube.com/watch?v=24eJqiOufNA']
['https://www.youtube.com/watch?v=u4DdR3riuy0']
['https://www.youtube.com/watch?v=DVRb4dm9Hqw']
['https://www.youtube.com/watch?v=h_p7dFjTWlw']
['https://www.youtube.com/watch?v=VQGDwGQ8GUg']
['https://www.youtube.com/watch?v=1rAaXu5344k']
['https://www.youtube.com/watch?v=geSvydlzsHo']
['https://www.youtube.com/watch?v=a0WXxErH4WU']


In [16]:
file_path = '/Users/itsyuzhou/Autumn2023/MA_thesis_repo/video_urls/fox_urls_2021.csv'
fox_2021 = read_csv_select_links(file_path)

for line in fox_2021:
    print(line)

['https://www.youtube.com/watch?v=ddLF4TxhlrY']
['https://www.youtube.com/watch?v=K0OWqZWV3E4']
['https://www.youtube.com/watch?v=I6rlnGLKE_4']
['https://www.youtube.com/watch?v=mvi4wTwEfIw']
['https://www.youtube.com/watch?v=dCgUTUdFVlk']
['https://www.youtube.com/watch?v=faRC9uXv3sw']
['https://www.youtube.com/watch?v=FyDyXsCEIRw']
['https://www.youtube.com/watch?v=VlseO1ZKDp4']
['https://www.youtube.com/watch?v=55ytQzdFDZg']
['https://www.youtube.com/watch?v=JPU7lmS438k']
['https://www.youtube.com/watch?v=FH3_L27qwWs']
['https://www.youtube.com/watch?v=M0ja1CkMFa4']


In [17]:
file_path = '/Users/itsyuzhou/Autumn2023/MA_thesis_repo/video_urls/abc_url.csv'
abc_2020 = read_csv_select_links(file_path)

for line in abc_2020:
    print(line)

['https://www.youtube.com/watch?v=L3T-3lvgC18']
['https://www.youtube.com/watch?v=nRnf-mHBrF8']
['https://www.youtube.com/watch?v=PHV4ukogdE0']
['https://www.youtube.com/watch?v=WQuAbkXU7dQ']
['https://www.youtube.com/watch?v=dz_klXK7xD8']
['https://www.youtube.com/watch?v=2vuG8a0lnvM']
['https://www.youtube.com/watch?v=W_R0L6_RhjE']
['https://www.youtube.com/watch?v=F56RBUercfI']
['https://www.youtube.com/watch?v=0IBU9-9FGeo']
['https://www.youtube.com/watch?v=0BSy4xWwf6Y']
['https://www.youtube.com/watch?v=g1PFqFVbBfQ']
['https://www.youtube.com/watch?v=nwwwqre28EQ']


In [18]:
file_path = '/Users/itsyuzhou/Autumn2023/MA_thesis_repo/video_urls/abc_urls_2021.csv'
abc_2021 = read_csv_select_links(file_path)

for line in abc_2021:
    print(line)

['https://www.youtube.com/watch?v=zMjZ2EwKWlk']
['https://www.youtube.com/watch?v=qEEMjrpJ_4w']
['https://www.youtube.com/watch?v=SFC5ZvULzJI']
['https://www.youtube.com/watch?v=5_osR3zb7dQ']
['https://www.youtube.com/watch?v=GQ20OnoAZks']
['https://www.youtube.com/watch?v=MaWCe5brzSs']
['https://www.youtube.com/watch?v=IJjdqAe8VJk']
['https://www.youtube.com/watch?v=ed1qT2_aTy0']
['https://www.youtube.com/watch?v=5s-boLTBCSc']
['https://www.youtube.com/watch?v=2dqcGqYdTXE']
['https://www.youtube.com/watch?v=DbBmE67T4r8']
['https://www.youtube.com/watch?v=4r7xgs-2_xE']


In [19]:
file_path = '/Users/itsyuzhou/Autumn2023/MA_thesis_repo/video_urls/msnbc_urls_2020.csv'
msnbc_2020 = read_csv_select_links(file_path)

for line in msnbc_2020:
    print(line)

['https://www.youtube.com/watch?v=on6Cs60axME']
['https://www.youtube.com/watch?v=NyyGyxBOlpE']
['https://www.youtube.com/watch?v=F8aueQXQ2H4']
['https://www.youtube.com/watch?v=eEup9pErtmM']
['https://www.youtube.com/watch?v=MlQ8A3GIBlY']
['https://www.youtube.com/watch?v=dQ06tls6_ys']
['https://www.youtube.com/watch?v=42qGSrtkqxU']
['https://www.youtube.com/watch?v=5fBOvOAw4xs']
['https://www.youtube.com/watch?v=3D2f36_VhtU']
['https://www.youtube.com/watch?v=DYwCyd0DtFI']
['https://www.youtube.com/watch?v=e66H6HC8amM']
['https://www.youtube.com/watch?v=uqyD0R7HRbY']


In [20]:
file_path = '/Users/itsyuzhou/Autumn2023/MA_thesis_repo/video_urls/msnbc_urls_2021.csv'
msnbc_2021 = read_csv_select_links(file_path)

for line in msnbc_2021:
    print(line)

['https://www.youtube.com/watch?v=PkHDgkiKRdU']
['https://www.youtube.com/watch?v=pi2Fi84Ytxg']
['https://www.youtube.com/watch?v=sM83s4ehWd0']
['https://www.youtube.com/watch?v=Jd2013SrRGA']
['https://www.youtube.com/watch?v=nhpnUyipiFw']
['https://www.youtube.com/watch?v=3P11TsAUJH4']
['https://www.youtube.com/watch?v=d7RurkwEpnw']
['https://www.youtube.com/watch?v=tjXbTRMyOx8']
['https://www.youtube.com/watch?v=EtEoMjf9pC0']
['https://www.youtube.com/watch?v=QSbVbIntS3Y']
['https://www.youtube.com/watch?v=ejfYQw_dO8o']
['https://www.youtube.com/watch?v=l3rPpAqVkNk']
